// Copyright 2017 Intel Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// -----------------------------------------------------------------------------

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: protobuf/client_block_pb2/client_block.proto

package client_block_pb2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	block_pb2 "github.com/hyperledger/sawtooth-sdk-go/protobuf/block_pb2"
	client_list_control_pb2 "github.com/hyperledger/sawtooth-sdk-go/protobuf/client_list_control_pb2"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientBlockListResponse_Status int32

const (
	ClientBlockListResponse_STATUS_UNSET   ClientBlockListResponse_Status = 0
	ClientBlockListResponse_OK             ClientBlockListResponse_Status = 1
	ClientBlockListResponse_INTERNAL_ERROR ClientBlockListResponse_Status = 2
	ClientBlockListResponse_NOT_READY      ClientBlockListResponse_Status = 3
	ClientBlockListResponse_NO_ROOT        ClientBlockListResponse_Status = 4
	ClientBlockListResponse_NO_RESOURCE    ClientBlockListResponse_Status = 5
	ClientBlockListResponse_INVALID_PAGING ClientBlockListResponse_Status = 6
	ClientBlockListResponse_INVALID_SORT   ClientBlockListResponse_Status = 7
	ClientBlockListResponse_INVALID_ID     ClientBlockListResponse_Status = 8
)

// Enum value maps for ClientBlockListResponse_Status.
var (
	ClientBlockListResponse_Status_name = map[int32]string{
		0: "STATUS_UNSET",
		1: "OK",
		2: "INTERNAL_ERROR",
		3: "NOT_READY",
		4: "NO_ROOT",
		5: "NO_RESOURCE",
		6: "INVALID_PAGING",
		7: "INVALID_SORT",
		8: "INVALID_ID",
	}
	ClientBlockListResponse_Status_value = map[string]int32{
		"STATUS_UNSET":   0,
		"OK":             1,
		"INTERNAL_ERROR": 2,
		"NOT_READY":      3,
		"NO_ROOT":        4,
		"NO_RESOURCE":    5,
		"INVALID_PAGING": 6,
		"INVALID_SORT":   7,
		"INVALID_ID":     8,
	}
)

func (x ClientBlockListResponse_Status) Enum() *ClientBlockListResponse_Status {
	p := new(ClientBlockListResponse_Status)
	*p = x
	return p
}

func (x ClientBlockListResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientBlockListResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_client_block_pb2_client_block_proto_enumTypes[0].Descriptor()
}

func (ClientBlockListResponse_Status) Type() protoreflect.EnumType {
	return &file_protobuf_client_block_pb2_client_block_proto_enumTypes[0]
}

func (x ClientBlockListResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientBlockListResponse_Status.Descriptor instead.
func (ClientBlockListResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_client_block_pb2_client_block_proto_rawDescGZIP(), []int{1, 0}
}

type ClientBlockGetResponse_Status int32

const (
	ClientBlockGetResponse_STATUS_UNSET   ClientBlockGetResponse_Status = 0
	ClientBlockGetResponse_OK             ClientBlockGetResponse_Status = 1
	ClientBlockGetResponse_INTERNAL_ERROR ClientBlockGetResponse_Status = 2
	ClientBlockGetResponse_NO_RESOURCE    ClientBlockGetResponse_Status = 5
	ClientBlockGetResponse_INVALID_ID     ClientBlockGetResponse_Status = 8
)

// Enum value maps for ClientBlockGetResponse_Status.
var (
	ClientBlockGetResponse_Status_name = map[int32]string{
		0: "STATUS_UNSET",
		1: "OK",
		2: "INTERNAL_ERROR",
		5: "NO_RESOURCE",
		8: "INVALID_ID",
	}
	ClientBlockGetResponse_Status_value = map[string]int32{
		"STATUS_UNSET":   0,
		"OK":             1,
		"INTERNAL_ERROR": 2,
		"NO_RESOURCE":    5,
		"INVALID_ID":     8,
	}
)

func (x ClientBlockGetResponse_Status) Enum() *ClientBlockGetResponse_Status {
	p := new(ClientBlockGetResponse_Status)
	*p = x
	return p
}

func (x ClientBlockGetResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientBlockGetResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_client_block_pb2_client_block_proto_enumTypes[1].Descriptor()
}

func (ClientBlockGetResponse_Status) Type() protoreflect.EnumType {
	return &file_protobuf_client_block_pb2_client_block_proto_enumTypes[1]
}

func (x ClientBlockGetResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientBlockGetResponse_Status.Descriptor instead.
func (ClientBlockGetResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_client_block_pb2_client_block_proto_rawDescGZIP(), []int{6, 0}
}

// A request to return a list of blocks from the validator. May include the id
// of a particular block to be the `head` of the chain being requested. In that
// case the list will include that block (if found), and all blocks previous
// to it on the chain. Can be filtered using specific `block_ids`.
type ClientBlockListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeadId   string                                        `protobuf:"bytes,1,opt,name=head_id,json=headId,proto3" json:"head_id,omitempty"`
	BlockIds []string                                      `protobuf:"bytes,2,rep,name=block_ids,json=blockIds,proto3" json:"block_ids,omitempty"`
	Paging   *client_list_control_pb2.ClientPagingControls `protobuf:"bytes,3,opt,name=paging,proto3" json:"paging,omitempty"`
	Sorting  []*client_list_control_pb2.ClientSortControls `protobuf:"bytes,4,rep,name=sorting,proto3" json:"sorting,omitempty"`
}

func (x *ClientBlockListRequest) Reset() {
	*x = ClientBlockListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_client_block_pb2_client_block_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientBlockListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientBlockListRequest) ProtoMessage() {}

func (x *ClientBlockListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_client_block_pb2_client_block_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientBlockListRequest.ProtoReflect.Descriptor instead.
func (*ClientBlockListRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_client_block_pb2_client_block_proto_rawDescGZIP(), []int{0}
}

func (x *ClientBlockListRequest) GetHeadId() string {
	if x != nil {
		return x.HeadId
	}
	return ""
}

func (x *ClientBlockListRequest) GetBlockIds() []string {
	if x != nil {
		return x.BlockIds
	}
	return nil
}

func (x *ClientBlockListRequest) GetPaging() *client_list_control_pb2.ClientPagingControls {
	if x != nil {
		return x.Paging
	}
	return nil
}

func (x *ClientBlockListRequest) GetSorting() []*client_list_control_pb2.ClientSortControls {
	if x != nil {
		return x.Sorting
	}
	return nil
}

// A response that lists a chain of blocks with the newest at the beginning,
// and the oldest (genesis) block at the end.
//
// Statuses:
//   * OK - everything worked as expected
//   * INTERNAL_ERROR - general error, such as protobuf failing to deserialize
//   * NOT_READY - the validator does not yet have a genesis block
//   * NO_ROOT - the head block specified was not found
//   * NO_RESOURCE - no blocks were found with the parameters specified
//   * INVALID_PAGING - the paging controls were malformed or out of range
//   * INVALID_SORT - the sorting controls were malformed or invalid
type ClientBlockListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status ClientBlockListResponse_Status                `protobuf:"varint,1,opt,name=status,proto3,enum=ClientBlockListResponse_Status" json:"status,omitempty"`
	Blocks []*block_pb2.Block                            `protobuf:"bytes,2,rep,name=blocks,proto3" json:"blocks,omitempty"`
	HeadId string                                        `protobuf:"bytes,3,opt,name=head_id,json=headId,proto3" json:"head_id,omitempty"`
	Paging *client_list_control_pb2.ClientPagingResponse `protobuf:"bytes,4,opt,name=paging,proto3" json:"paging,omitempty"`
}

func (x *ClientBlockListResponse) Reset() {
	*x = ClientBlockListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_client_block_pb2_client_block_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientBlockListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientBlockListResponse) ProtoMessage() {}

func (x *ClientBlockListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_client_block_pb2_client_block_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientBlockListResponse.ProtoReflect.Descriptor instead.
func (*ClientBlockListResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_client_block_pb2_client_block_proto_rawDescGZIP(), []int{1}
}

func (x *ClientBlockListResponse) GetStatus() ClientBlockListResponse_Status {
	if x != nil {
		return x.Status
	}
	return ClientBlockListResponse_STATUS_UNSET
}

func (x *ClientBlockListResponse) GetBlocks() []*block_pb2.Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

func (x *ClientBlockListResponse) GetHeadId() string {
	if x != nil {
		return x.HeadId
	}
	return ""
}

func (x *ClientBlockListResponse) GetPaging() *client_list_control_pb2.ClientPagingResponse {
	if x != nil {
		return x.Paging
	}
	return nil
}

// A request to return a specific block from the validator. The block must be
// specified by its unique id, in this case the block's header signature
type ClientBlockGetByIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockId string `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
}

func (x *ClientBlockGetByIdRequest) Reset() {
	*x = ClientBlockGetByIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_client_block_pb2_client_block_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientBlockGetByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientBlockGetByIdRequest) ProtoMessage() {}

func (x *ClientBlockGetByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_client_block_pb2_client_block_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientBlockGetByIdRequest.ProtoReflect.Descriptor instead.
func (*ClientBlockGetByIdRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_client_block_pb2_client_block_proto_rawDescGZIP(), []int{2}
}

func (x *ClientBlockGetByIdRequest) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

// A request to return a specific block from the validator. The block must be
// specified by its block number
type ClientBlockGetByNumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlockNum uint64 `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
}

func (x *ClientBlockGetByNumRequest) Reset() {
	*x = ClientBlockGetByNumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_client_block_pb2_client_block_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientBlockGetByNumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientBlockGetByNumRequest) ProtoMessage() {}

func (x *ClientBlockGetByNumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_client_block_pb2_client_block_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientBlockGetByNumRequest.ProtoReflect.Descriptor instead.
func (*ClientBlockGetByNumRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_client_block_pb2_client_block_proto_rawDescGZIP(), []int{3}
}

func (x *ClientBlockGetByNumRequest) GetBlockNum() uint64 {
	if x != nil {
		return x.BlockNum
	}
	return 0
}

// A request to return a specific block from the validator. The block
// containing the given transaction is returned. If no block on the current
// chain contains the transaction, NO_RESOURCE is returned.
type ClientBlockGetByTransactionIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransactionId string `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
}

func (x *ClientBlockGetByTransactionIdRequest) Reset() {
	*x = ClientBlockGetByTransactionIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_client_block_pb2_client_block_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientBlockGetByTransactionIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientBlockGetByTransactionIdRequest) ProtoMessage() {}

func (x *ClientBlockGetByTransactionIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_client_block_pb2_client_block_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientBlockGetByTransactionIdRequest.ProtoReflect.Descriptor instead.
func (*ClientBlockGetByTransactionIdRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_client_block_pb2_client_block_proto_rawDescGZIP(), []int{4}
}

func (x *ClientBlockGetByTransactionIdRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

// A request to return a specific block from the validator. The block
// containing the given batch is returned. If no block on the current chain
// contains the batch, NO_RESOURCE is returned.
type ClientBlockGetByBatchIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BatchId string `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
}

func (x *ClientBlockGetByBatchIdRequest) Reset() {
	*x = ClientBlockGetByBatchIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_client_block_pb2_client_block_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientBlockGetByBatchIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientBlockGetByBatchIdRequest) ProtoMessage() {}

func (x *ClientBlockGetByBatchIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_client_block_pb2_client_block_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientBlockGetByBatchIdRequest.ProtoReflect.Descriptor instead.
func (*ClientBlockGetByBatchIdRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_client_block_pb2_client_block_proto_rawDescGZIP(), []int{5}
}

func (x *ClientBlockGetByBatchIdRequest) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

// A response that returns the block specified by a ClientBlockGetByIdRequest
// or  ClientBlockGetByNumRequest.
//
// Statuses:
//   * OK - everything worked as expected
//   * INTERNAL_ERROR - general error, such as protobuf failing to deserialize
//   * NO_RESOURCE - no block with the specified id exists
type ClientBlockGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status ClientBlockGetResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=ClientBlockGetResponse_Status" json:"status,omitempty"`
	Block  *block_pb2.Block              `protobuf:"bytes,2,opt,name=block,proto3" json:"block,omitempty"`
}

func (x *ClientBlockGetResponse) Reset() {
	*x = ClientBlockGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_client_block_pb2_client_block_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientBlockGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientBlockGetResponse) ProtoMessage() {}

func (x *ClientBlockGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_client_block_pb2_client_block_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientBlockGetResponse.ProtoReflect.Descriptor instead.
func (*ClientBlockGetResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_client_block_pb2_client_block_proto_rawDescGZIP(), []int{6}
}

func (x *ClientBlockGetResponse) GetStatus() ClientBlockGetResponse_Status {
	if x != nil {
		return x.Status
	}
	return ClientBlockGetResponse_STATUS_UNSET
}

func (x *ClientBlockGetResponse) GetBlock() *block_pb2.Block {
	if x != nil {
		return x.Block
	}
	return nil
}

var File_protobuf_client_block_pb2_client_block_proto protoreflect.FileDescriptor

var file_protobuf_client_block_pb2_client_block_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x70, 0x62, 0x32, 0x2f, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x70,
	0x62, 0x32, 0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x3a,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x70, 0x62, 0x32,
	0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xac, 0x01, 0x0a, 0x16, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x49, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x08, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x73, 0x12, 0x2d, 0x0a, 0x06, 0x70,
	0x61, 0x67, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x73, 0x52, 0x06, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x12, 0x2d, 0x0a, 0x07, 0x73, 0x6f,
	0x72, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x53, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x73,
	0x52, 0x07, 0x73, 0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x22, 0xd6, 0x02, 0x0a, 0x17, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e,
	0x0a, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x06,
	0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x12, 0x17,
	0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x68, 0x65, 0x61, 0x64, 0x49, 0x64, 0x12, 0x2d, 0x0a, 0x06, 0x70, 0x61, 0x67, 0x69, 0x6e,
	0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x50, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x06,
	0x70, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x22, 0x99, 0x01, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x45,
	0x54, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x49,
	0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x02, 0x12,
	0x0d, 0x0a, 0x09, 0x4e, 0x4f, 0x54, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x59, 0x10, 0x03, 0x12, 0x0b,
	0x0a, 0x07, 0x4e, 0x4f, 0x5f, 0x52, 0x4f, 0x4f, 0x54, 0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b, 0x4e,
	0x4f, 0x5f, 0x52, 0x45, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x10, 0x05, 0x12, 0x12, 0x0a, 0x0e,
	0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x50, 0x41, 0x47, 0x49, 0x4e, 0x47, 0x10, 0x06,
	0x12, 0x10, 0x0a, 0x0c, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x53, 0x4f, 0x52, 0x54,
	0x10, 0x07, 0x12, 0x0e, 0x0a, 0x0a, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x49, 0x44,
	0x10, 0x08, 0x22, 0x36, 0x0a, 0x19, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x47, 0x65, 0x74, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x19, 0x0a, 0x08, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x22, 0x39, 0x0a, 0x1a, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x47, 0x65, 0x74, 0x42, 0x79, 0x4e, 0x75,
	0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x22, 0x4d, 0x0a, 0x24, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x47, 0x65, 0x74, 0x42, 0x79, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a,
	0x0e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x22, 0x3b, 0x0a, 0x1e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x47, 0x65, 0x74, 0x42, 0x79, 0x42, 0x61, 0x74, 0x63, 0x68, 0x49, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x61, 0x74, 0x63, 0x68, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x61, 0x74, 0x63, 0x68, 0x49,
	0x64, 0x22, 0xc7, 0x01, 0x0a, 0x16, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x1c, 0x0a, 0x05, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x05, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x22, 0x57, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x0c,
	0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x45, 0x54, 0x10, 0x00, 0x12, 0x06,
	0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e,
	0x41, 0x4c, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x4e, 0x4f,
	0x5f, 0x52, 0x45, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x10, 0x05, 0x12, 0x0e, 0x0a, 0x0a, 0x49,
	0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x49, 0x44, 0x10, 0x08, 0x42, 0x2b, 0x0a, 0x15, 0x73,
	0x61, 0x77, 0x74, 0x6f, 0x6f, 0x74, 0x68, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x50, 0x01, 0x5a, 0x10, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x70, 0x62, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_client_block_pb2_client_block_proto_rawDescOnce sync.Once
	file_protobuf_client_block_pb2_client_block_proto_rawDescData = file_protobuf_client_block_pb2_client_block_proto_rawDesc
)

func file_protobuf_client_block_pb2_client_block_proto_rawDescGZIP() []byte {
	file_protobuf_client_block_pb2_client_block_proto_rawDescOnce.Do(func() {
		file_protobuf_client_block_pb2_client_block_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_client_block_pb2_client_block_proto_rawDescData)
	})
	return file_protobuf_client_block_pb2_client_block_proto_rawDescData
}

var file_protobuf_client_block_pb2_client_block_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protobuf_client_block_pb2_client_block_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_protobuf_client_block_pb2_client_block_proto_goTypes = []interface{}{
	(ClientBlockListResponse_Status)(0),                  // 0: ClientBlockListResponse.Status
	(ClientBlockGetResponse_Status)(0),                   // 1: ClientBlockGetResponse.Status
	(*ClientBlockListRequest)(nil),                       // 2: ClientBlockListRequest
	(*ClientBlockListResponse)(nil),                      // 3: ClientBlockListResponse
	(*ClientBlockGetByIdRequest)(nil),                    // 4: ClientBlockGetByIdRequest
	(*ClientBlockGetByNumRequest)(nil),                   // 5: ClientBlockGetByNumRequest
	(*ClientBlockGetByTransactionIdRequest)(nil),         // 6: ClientBlockGetByTransactionIdRequest
	(*ClientBlockGetByBatchIdRequest)(nil),               // 7: ClientBlockGetByBatchIdRequest
	(*ClientBlockGetResponse)(nil),                       // 8: ClientBlockGetResponse
	(*client_list_control_pb2.ClientPagingControls)(nil), // 9: ClientPagingControls
	(*client_list_control_pb2.ClientSortControls)(nil),   // 10: ClientSortControls
	(*block_pb2.Block)(nil),                              // 11: Block
	(*client_list_control_pb2.ClientPagingResponse)(nil), // 12: ClientPagingResponse
}
var file_protobuf_client_block_pb2_client_block_proto_depIdxs = []int32{
	9,  // 0: ClientBlockListRequest.paging:type_name -> ClientPagingControls
	10, // 1: ClientBlockListRequest.sorting:type_name -> ClientSortControls
	0,  // 2: ClientBlockListResponse.status:type_name -> ClientBlockListResponse.Status
	11, // 3: ClientBlockListResponse.blocks:type_name -> Block
	12, // 4: ClientBlockListResponse.paging:type_name -> ClientPagingResponse
	1,  // 5: ClientBlockGetResponse.status:type_name -> ClientBlockGetResponse.Status
	11, // 6: ClientBlockGetResponse.block:type_name -> Block
	7,  // [7:7] is the sub-list for method output_type
	7,  // [7:7] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_protobuf_client_block_pb2_client_block_proto_init() }
func file_protobuf_client_block_pb2_client_block_proto_init() {
	if File_protobuf_client_block_pb2_client_block_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_client_block_pb2_client_block_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientBlockListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_client_block_pb2_client_block_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientBlockListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_client_block_pb2_client_block_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientBlockGetByIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_client_block_pb2_client_block_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientBlockGetByNumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_client_block_pb2_client_block_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientBlockGetByTransactionIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_client_block_pb2_client_block_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientBlockGetByBatchIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_client_block_pb2_client_block_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientBlockGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_client_block_pb2_client_block_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_client_block_pb2_client_block_proto_goTypes,
		DependencyIndexes: file_protobuf_client_block_pb2_client_block_proto_depIdxs,
		EnumInfos:         file_protobuf_client_block_pb2_client_block_proto_enumTypes,
		MessageInfos:      file_protobuf_client_block_pb2_client_block_proto_msgTypes,
	}.Build()
	File_protobuf_client_block_pb2_client_block_proto = out.File
	file_protobuf_client_block_pb2_client_block_proto_rawDesc = nil
	file_protobuf_client_block_pb2_client_block_proto_goTypes = nil
	file_protobuf_client_block_pb2_client_block_proto_depIdxs = nil
}
