// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/client_batch_pb2/client_batch.proto

package client_batch_pb2

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	batch_pb2 "protobuf/batch_pb2"
	client_list_control_pb2 "protobuf/client_list_control_pb2"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClientBatchListResponse_Status int32

const (
	ClientBatchListResponse_STATUS_UNSET   ClientBatchListResponse_Status = 0
	ClientBatchListResponse_OK             ClientBatchListResponse_Status = 1
	ClientBatchListResponse_INTERNAL_ERROR ClientBatchListResponse_Status = 2
	ClientBatchListResponse_NOT_READY      ClientBatchListResponse_Status = 3
	ClientBatchListResponse_NO_ROOT        ClientBatchListResponse_Status = 4
	ClientBatchListResponse_NO_RESOURCE    ClientBatchListResponse_Status = 5
	ClientBatchListResponse_INVALID_PAGING ClientBatchListResponse_Status = 6
	ClientBatchListResponse_INVALID_SORT   ClientBatchListResponse_Status = 7
	ClientBatchListResponse_INVALID_ID     ClientBatchListResponse_Status = 8
)

var ClientBatchListResponse_Status_name = map[int32]string{
	0: "STATUS_UNSET",
	1: "OK",
	2: "INTERNAL_ERROR",
	3: "NOT_READY",
	4: "NO_ROOT",
	5: "NO_RESOURCE",
	6: "INVALID_PAGING",
	7: "INVALID_SORT",
	8: "INVALID_ID",
}

var ClientBatchListResponse_Status_value = map[string]int32{
	"STATUS_UNSET":   0,
	"OK":             1,
	"INTERNAL_ERROR": 2,
	"NOT_READY":      3,
	"NO_ROOT":        4,
	"NO_RESOURCE":    5,
	"INVALID_PAGING": 6,
	"INVALID_SORT":   7,
	"INVALID_ID":     8,
}

func (x ClientBatchListResponse_Status) String() string {
	return proto.EnumName(ClientBatchListResponse_Status_name, int32(x))
}

func (ClientBatchListResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e45770b69bcdf1e4, []int{1, 0}
}

type ClientBatchGetResponse_Status int32

const (
	ClientBatchGetResponse_STATUS_UNSET   ClientBatchGetResponse_Status = 0
	ClientBatchGetResponse_OK             ClientBatchGetResponse_Status = 1
	ClientBatchGetResponse_INTERNAL_ERROR ClientBatchGetResponse_Status = 2
	ClientBatchGetResponse_NO_RESOURCE    ClientBatchGetResponse_Status = 5
	ClientBatchGetResponse_INVALID_ID     ClientBatchGetResponse_Status = 8
)

var ClientBatchGetResponse_Status_name = map[int32]string{
	0: "STATUS_UNSET",
	1: "OK",
	2: "INTERNAL_ERROR",
	5: "NO_RESOURCE",
	8: "INVALID_ID",
}

var ClientBatchGetResponse_Status_value = map[string]int32{
	"STATUS_UNSET":   0,
	"OK":             1,
	"INTERNAL_ERROR": 2,
	"NO_RESOURCE":    5,
	"INVALID_ID":     8,
}

func (x ClientBatchGetResponse_Status) String() string {
	return proto.EnumName(ClientBatchGetResponse_Status_name, int32(x))
}

func (ClientBatchGetResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e45770b69bcdf1e4, []int{3, 0}
}

// A request to return a list of batches from the validator. May include the id
// of a particular block to be the `head` of the chain being requested. In that
// case the list will include the batches from that block, and all batches
// previous to that block on the chain. Filter with specific `batch_ids`.
type ClientBatchListRequest struct {
	HeadId               string                                        `protobuf:"bytes,1,opt,name=head_id,json=headId,proto3" json:"head_id,omitempty"`
	BatchIds             []string                                      `protobuf:"bytes,2,rep,name=batch_ids,json=batchIds,proto3" json:"batch_ids,omitempty"`
	Paging               *client_list_control_pb2.ClientPagingControls `protobuf:"bytes,3,opt,name=paging,proto3" json:"paging,omitempty"`
	Sorting              []*client_list_control_pb2.ClientSortControls `protobuf:"bytes,4,rep,name=sorting,proto3" json:"sorting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                      `json:"-"`
	XXX_unrecognized     []byte                                        `json:"-"`
	XXX_sizecache        int32                                         `json:"-"`
}

func (m *ClientBatchListRequest) Reset()         { *m = ClientBatchListRequest{} }
func (m *ClientBatchListRequest) String() string { return proto.CompactTextString(m) }
func (*ClientBatchListRequest) ProtoMessage()    {}
func (*ClientBatchListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e45770b69bcdf1e4, []int{0}
}

func (m *ClientBatchListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientBatchListRequest.Unmarshal(m, b)
}
func (m *ClientBatchListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientBatchListRequest.Marshal(b, m, deterministic)
}
func (m *ClientBatchListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientBatchListRequest.Merge(m, src)
}
func (m *ClientBatchListRequest) XXX_Size() int {
	return xxx_messageInfo_ClientBatchListRequest.Size(m)
}
func (m *ClientBatchListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientBatchListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClientBatchListRequest proto.InternalMessageInfo

func (m *ClientBatchListRequest) GetHeadId() string {
	if m != nil {
		return m.HeadId
	}
	return ""
}

func (m *ClientBatchListRequest) GetBatchIds() []string {
	if m != nil {
		return m.BatchIds
	}
	return nil
}

func (m *ClientBatchListRequest) GetPaging() *client_list_control_pb2.ClientPagingControls {
	if m != nil {
		return m.Paging
	}
	return nil
}

func (m *ClientBatchListRequest) GetSorting() []*client_list_control_pb2.ClientSortControls {
	if m != nil {
		return m.Sorting
	}
	return nil
}

// A response that lists batches from newest to oldest.
//
// Statuses:
//   * OK - everything worked as expected
//   * INTERNAL_ERROR - general error, such as protobuf failing to deserialize
//   * NOT_READY - the validator does not yet have a genesis block
//   * NO_ROOT - the head block specified was not found
//   * NO_RESOURCE - no batches were found with the parameters specified
//   * INVALID_PAGING - the paging controls were malformed or out of range
//   * INVALID_SORT - the sorting controls were malformed or invalid
type ClientBatchListResponse struct {
	Status               ClientBatchListResponse_Status                `protobuf:"varint,1,opt,name=status,proto3,enum=ClientBatchListResponse_Status" json:"status,omitempty"`
	Batches              []*batch_pb2.Batch                            `protobuf:"bytes,2,rep,name=batches,proto3" json:"batches,omitempty"`
	HeadId               string                                        `protobuf:"bytes,3,opt,name=head_id,json=headId,proto3" json:"head_id,omitempty"`
	Paging               *client_list_control_pb2.ClientPagingResponse `protobuf:"bytes,4,opt,name=paging,proto3" json:"paging,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                      `json:"-"`
	XXX_unrecognized     []byte                                        `json:"-"`
	XXX_sizecache        int32                                         `json:"-"`
}

func (m *ClientBatchListResponse) Reset()         { *m = ClientBatchListResponse{} }
func (m *ClientBatchListResponse) String() string { return proto.CompactTextString(m) }
func (*ClientBatchListResponse) ProtoMessage()    {}
func (*ClientBatchListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e45770b69bcdf1e4, []int{1}
}

func (m *ClientBatchListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientBatchListResponse.Unmarshal(m, b)
}
func (m *ClientBatchListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientBatchListResponse.Marshal(b, m, deterministic)
}
func (m *ClientBatchListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientBatchListResponse.Merge(m, src)
}
func (m *ClientBatchListResponse) XXX_Size() int {
	return xxx_messageInfo_ClientBatchListResponse.Size(m)
}
func (m *ClientBatchListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientBatchListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClientBatchListResponse proto.InternalMessageInfo

func (m *ClientBatchListResponse) GetStatus() ClientBatchListResponse_Status {
	if m != nil {
		return m.Status
	}
	return ClientBatchListResponse_STATUS_UNSET
}

func (m *ClientBatchListResponse) GetBatches() []*batch_pb2.Batch {
	if m != nil {
		return m.Batches
	}
	return nil
}

func (m *ClientBatchListResponse) GetHeadId() string {
	if m != nil {
		return m.HeadId
	}
	return ""
}

func (m *ClientBatchListResponse) GetPaging() *client_list_control_pb2.ClientPagingResponse {
	if m != nil {
		return m.Paging
	}
	return nil
}

// Fetches a specific batch by its id (header_signature) from the blockchain.
type ClientBatchGetRequest struct {
	BatchId              string   `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientBatchGetRequest) Reset()         { *m = ClientBatchGetRequest{} }
func (m *ClientBatchGetRequest) String() string { return proto.CompactTextString(m) }
func (*ClientBatchGetRequest) ProtoMessage()    {}
func (*ClientBatchGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e45770b69bcdf1e4, []int{2}
}

func (m *ClientBatchGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientBatchGetRequest.Unmarshal(m, b)
}
func (m *ClientBatchGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientBatchGetRequest.Marshal(b, m, deterministic)
}
func (m *ClientBatchGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientBatchGetRequest.Merge(m, src)
}
func (m *ClientBatchGetRequest) XXX_Size() int {
	return xxx_messageInfo_ClientBatchGetRequest.Size(m)
}
func (m *ClientBatchGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientBatchGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClientBatchGetRequest proto.InternalMessageInfo

func (m *ClientBatchGetRequest) GetBatchId() string {
	if m != nil {
		return m.BatchId
	}
	return ""
}

// A response that returns the batch specified by a ClientBatchGetRequest.
//
// Statuses:
//   * OK - everything worked as expected, batch has been fetched
//   * INTERNAL_ERROR - general error, such as protobuf failing to deserialize
//   * NO_RESOURCE - no batch with the specified id exists
type ClientBatchGetResponse struct {
	Status               ClientBatchGetResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=ClientBatchGetResponse_Status" json:"status,omitempty"`
	Batch                *batch_pb2.Batch              `protobuf:"bytes,2,opt,name=batch,proto3" json:"batch,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *ClientBatchGetResponse) Reset()         { *m = ClientBatchGetResponse{} }
func (m *ClientBatchGetResponse) String() string { return proto.CompactTextString(m) }
func (*ClientBatchGetResponse) ProtoMessage()    {}
func (*ClientBatchGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e45770b69bcdf1e4, []int{3}
}

func (m *ClientBatchGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientBatchGetResponse.Unmarshal(m, b)
}
func (m *ClientBatchGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientBatchGetResponse.Marshal(b, m, deterministic)
}
func (m *ClientBatchGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientBatchGetResponse.Merge(m, src)
}
func (m *ClientBatchGetResponse) XXX_Size() int {
	return xxx_messageInfo_ClientBatchGetResponse.Size(m)
}
func (m *ClientBatchGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientBatchGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClientBatchGetResponse proto.InternalMessageInfo

func (m *ClientBatchGetResponse) GetStatus() ClientBatchGetResponse_Status {
	if m != nil {
		return m.Status
	}
	return ClientBatchGetResponse_STATUS_UNSET
}

func (m *ClientBatchGetResponse) GetBatch() *batch_pb2.Batch {
	if m != nil {
		return m.Batch
	}
	return nil
}

func init() {
	proto.RegisterEnum("ClientBatchListResponse_Status", ClientBatchListResponse_Status_name, ClientBatchListResponse_Status_value)
	proto.RegisterEnum("ClientBatchGetResponse_Status", ClientBatchGetResponse_Status_name, ClientBatchGetResponse_Status_value)
	proto.RegisterType((*ClientBatchListRequest)(nil), "ClientBatchListRequest")
	proto.RegisterType((*ClientBatchListResponse)(nil), "ClientBatchListResponse")
	proto.RegisterType((*ClientBatchGetRequest)(nil), "ClientBatchGetRequest")
	proto.RegisterType((*ClientBatchGetResponse)(nil), "ClientBatchGetResponse")
}

func init() {
	proto.RegisterFile("protobuf/client_batch_pb2/client_batch.proto", fileDescriptor_e45770b69bcdf1e4)
}

var fileDescriptor_e45770b69bcdf1e4 = []byte{
	// 484 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0xdd, 0x8e, 0x93, 0x40,
	0x14, 0xc7, 0x05, 0xba, 0xd0, 0x1e, 0xb4, 0x4e, 0xc6, 0xd4, 0xad, 0x1f, 0x59, 0x09, 0x57, 0x4d,
	0x74, 0x31, 0xc1, 0x44, 0x13, 0xef, 0xd8, 0x96, 0x34, 0xc4, 0x06, 0x9a, 0x81, 0x6a, 0xf4, 0x86,
	0xd0, 0x82, 0x5b, 0x62, 0x53, 0x6a, 0x67, 0x1a, 0x9f, 0xc5, 0x77, 0xf0, 0x3d, 0x7c, 0x05, 0x1f,
	0xc7, 0x30, 0x30, 0x5d, 0xca, 0xae, 0x37, 0x5e, 0xce, 0x7f, 0x7e, 0x73, 0xbe, 0xfe, 0x67, 0xe0,
	0xd5, 0x6e, 0x5f, 0xb0, 0x62, 0x79, 0xf8, 0xfa, 0x7a, 0xb5, 0xc9, 0xb3, 0x2d, 0x8b, 0x97, 0x09,
	0x5b, 0xad, 0xe3, 0xdd, 0xd2, 0x3e, 0x11, 0x2c, 0x8e, 0x3d, 0xbd, 0x38, 0xd2, 0x37, 0x58, 0xf3,
	0xfe, 0x7d, 0x3b, 0xda, 0x26, 0xa7, 0x2c, 0x5e, 0x15, 0x5b, 0xb6, 0x2f, 0x36, 0xcd, 0xa0, 0x4d,
	0xbd, 0x7a, 0x6b, 0xfe, 0x92, 0xe0, 0xf1, 0x98, 0xdf, 0x5e, 0x95, 0x11, 0x67, 0x39, 0x65, 0x24,
	0xfb, 0x7e, 0xc8, 0x28, 0xc3, 0xe7, 0xa0, 0xad, 0xb3, 0x24, 0x8d, 0xf3, 0x74, 0x28, 0x19, 0xd2,
	0xa8, 0x47, 0xd4, 0xf2, 0xe8, 0xa5, 0xf8, 0x19, 0xf4, 0xaa, 0x42, 0xf2, 0x94, 0x0e, 0x65, 0x43,
	0x19, 0xf5, 0x48, 0x97, 0x0b, 0x5e, 0x4a, 0xf1, 0x25, 0xa8, 0xbb, 0xe4, 0x3a, 0xdf, 0x5e, 0x0f,
	0x15, 0x43, 0x1a, 0xe9, 0xf6, 0xc0, 0xaa, 0xc2, 0xcf, 0xb9, 0x38, 0xae, 0x92, 0x53, 0x52, 0x43,
	0xf8, 0x12, 0x34, 0x5a, 0xec, 0x59, 0xc9, 0x77, 0x0c, 0x65, 0xa4, 0xdb, 0x8f, 0x6a, 0x3e, 0x2c,
	0xf6, 0xec, 0x48, 0x0b, 0xc6, 0xfc, 0x23, 0xc3, 0xf9, 0xad, 0x72, 0xe9, 0xae, 0xd8, 0xd2, 0x0c,
	0xbf, 0x03, 0x95, 0xb2, 0x84, 0x1d, 0x28, 0x2f, 0xb7, 0x6f, 0xbf, 0xb0, 0xfe, 0x41, 0x5a, 0x21,
	0xc7, 0x48, 0x8d, 0x63, 0x03, 0x34, 0x5e, 0x7e, 0x56, 0x75, 0xa3, 0xdb, 0xaa, 0xc5, 0xdf, 0x10,
	0x21, 0x37, 0x47, 0xa1, 0x9c, 0x8c, 0xe2, 0xa6, 0xdb, 0xce, 0x1d, 0xdd, 0x8a, 0x84, 0xa2, 0x5b,
	0xf3, 0xa7, 0x04, 0x6a, 0x95, 0x1c, 0x23, 0xb8, 0x1f, 0x46, 0x4e, 0xb4, 0x08, 0xe3, 0x85, 0x1f,
	0xba, 0x11, 0xba, 0x87, 0x55, 0x90, 0x83, 0x0f, 0x48, 0xc2, 0x18, 0xfa, 0x9e, 0x1f, 0xb9, 0xc4,
	0x77, 0x66, 0xb1, 0x4b, 0x48, 0x40, 0x90, 0x8c, 0x1f, 0x40, 0xcf, 0x0f, 0xa2, 0x98, 0xb8, 0xce,
	0xe4, 0x33, 0x52, 0xb0, 0x0e, 0x9a, 0x1f, 0xc4, 0x24, 0x08, 0x22, 0xd4, 0xc1, 0x0f, 0x41, 0x2f,
	0x0f, 0x6e, 0x18, 0x2c, 0xc8, 0xd8, 0x45, 0x67, 0x55, 0x80, 0x8f, 0xce, 0xcc, 0x9b, 0xc4, 0x73,
	0x67, 0xea, 0xf9, 0x53, 0xa4, 0x96, 0xe9, 0x84, 0x16, 0x06, 0x24, 0x42, 0x1a, 0xee, 0x03, 0x08,
	0xc5, 0x9b, 0xa0, 0xae, 0x69, 0xc3, 0xa0, 0x31, 0xaf, 0x69, 0x76, 0xdc, 0x83, 0x27, 0xd0, 0x15,
	0x76, 0xd7, 0x8b, 0xa0, 0xd5, 0x6e, 0x9b, 0xbf, 0x4f, 0xb7, 0x87, 0x3f, 0xaa, 0xdd, 0x78, 0xdb,
	0x72, 0xe3, 0xc2, 0xba, 0x1b, 0x6c, 0x9b, 0xf1, 0x1c, 0xce, 0x78, 0xf4, 0xa1, 0xcc, 0x07, 0x2a,
	0xac, 0xa8, 0x44, 0xf3, 0xd3, 0x7f, 0xce, 0xef, 0xd6, 0x8c, 0x5a, 0xdd, 0x5f, 0xbd, 0x84, 0x01,
	0x4d, 0x7e, 0xb0, 0xa2, 0x60, 0x6b, 0x8b, 0xa6, 0xdf, 0x2c, 0xf1, 0xa5, 0xe6, 0xd2, 0x17, 0xd4,
	0xfe, 0xa3, 0x4b, 0x95, 0xdf, 0xbe, 0xf9, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xbe, 0xdf, 0x12, 0x9d,
	0xc7, 0x03, 0x00, 0x00,
}
