// Copyright 2017 Intel Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// -----------------------------------------------------------------------------

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: protobuf/client_transaction_pb2/client_transaction.proto

package client_transaction_pb2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	client_list_control_pb2 "github.com/hyperledger/sawtooth-sdk-go/protobuf/client_list_control_pb2"
	transaction_pb2 "github.com/hyperledger/sawtooth-sdk-go/protobuf/transaction_pb2"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientTransactionListResponse_Status int32

const (
	ClientTransactionListResponse_STATUS_UNSET   ClientTransactionListResponse_Status = 0
	ClientTransactionListResponse_OK             ClientTransactionListResponse_Status = 1
	ClientTransactionListResponse_INTERNAL_ERROR ClientTransactionListResponse_Status = 2
	ClientTransactionListResponse_NOT_READY      ClientTransactionListResponse_Status = 3
	ClientTransactionListResponse_NO_ROOT        ClientTransactionListResponse_Status = 4
	ClientTransactionListResponse_NO_RESOURCE    ClientTransactionListResponse_Status = 5
	ClientTransactionListResponse_INVALID_PAGING ClientTransactionListResponse_Status = 6
	ClientTransactionListResponse_INVALID_SORT   ClientTransactionListResponse_Status = 7
	ClientTransactionListResponse_INVALID_ID     ClientTransactionListResponse_Status = 8
)

// Enum value maps for ClientTransactionListResponse_Status.
var (
	ClientTransactionListResponse_Status_name = map[int32]string{
		0: "STATUS_UNSET",
		1: "OK",
		2: "INTERNAL_ERROR",
		3: "NOT_READY",
		4: "NO_ROOT",
		5: "NO_RESOURCE",
		6: "INVALID_PAGING",
		7: "INVALID_SORT",
		8: "INVALID_ID",
	}
	ClientTransactionListResponse_Status_value = map[string]int32{
		"STATUS_UNSET":   0,
		"OK":             1,
		"INTERNAL_ERROR": 2,
		"NOT_READY":      3,
		"NO_ROOT":        4,
		"NO_RESOURCE":    5,
		"INVALID_PAGING": 6,
		"INVALID_SORT":   7,
		"INVALID_ID":     8,
	}
)

func (x ClientTransactionListResponse_Status) Enum() *ClientTransactionListResponse_Status {
	p := new(ClientTransactionListResponse_Status)
	*p = x
	return p
}

func (x ClientTransactionListResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientTransactionListResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_client_transaction_pb2_client_transaction_proto_enumTypes[0].Descriptor()
}

func (ClientTransactionListResponse_Status) Type() protoreflect.EnumType {
	return &file_protobuf_client_transaction_pb2_client_transaction_proto_enumTypes[0]
}

func (x ClientTransactionListResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientTransactionListResponse_Status.Descriptor instead.
func (ClientTransactionListResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_client_transaction_pb2_client_transaction_proto_rawDescGZIP(), []int{1, 0}
}

type ClientTransactionGetResponse_Status int32

const (
	ClientTransactionGetResponse_STATUS_UNSET   ClientTransactionGetResponse_Status = 0
	ClientTransactionGetResponse_OK             ClientTransactionGetResponse_Status = 1
	ClientTransactionGetResponse_INTERNAL_ERROR ClientTransactionGetResponse_Status = 2
	ClientTransactionGetResponse_NO_RESOURCE    ClientTransactionGetResponse_Status = 5
	ClientTransactionGetResponse_INVALID_ID     ClientTransactionGetResponse_Status = 8
)

// Enum value maps for ClientTransactionGetResponse_Status.
var (
	ClientTransactionGetResponse_Status_name = map[int32]string{
		0: "STATUS_UNSET",
		1: "OK",
		2: "INTERNAL_ERROR",
		5: "NO_RESOURCE",
		8: "INVALID_ID",
	}
	ClientTransactionGetResponse_Status_value = map[string]int32{
		"STATUS_UNSET":   0,
		"OK":             1,
		"INTERNAL_ERROR": 2,
		"NO_RESOURCE":    5,
		"INVALID_ID":     8,
	}
)

func (x ClientTransactionGetResponse_Status) Enum() *ClientTransactionGetResponse_Status {
	p := new(ClientTransactionGetResponse_Status)
	*p = x
	return p
}

func (x ClientTransactionGetResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientTransactionGetResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_client_transaction_pb2_client_transaction_proto_enumTypes[1].Descriptor()
}

func (ClientTransactionGetResponse_Status) Type() protoreflect.EnumType {
	return &file_protobuf_client_transaction_pb2_client_transaction_proto_enumTypes[1]
}

func (x ClientTransactionGetResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientTransactionGetResponse_Status.Descriptor instead.
func (ClientTransactionGetResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_client_transaction_pb2_client_transaction_proto_rawDescGZIP(), []int{3, 0}
}

// A request to return a list of txns from the validator. May include the id
// of a particular block to be the `head` of the chain being requested. In that
// case the list will include the txns from that block, and all txns
// previous to that block on the chain. Filter with specific `transaction_ids`.
type ClientTransactionListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HeadId         string                                        `protobuf:"bytes,1,opt,name=head_id,json=headId,proto3" json:"head_id,omitempty"`
	TransactionIds []string                                      `protobuf:"bytes,2,rep,name=transaction_ids,json=transactionIds,proto3" json:"transaction_ids,omitempty"`
	Paging         *client_list_control_pb2.ClientPagingControls `protobuf:"bytes,3,opt,name=paging,proto3" json:"paging,omitempty"`
	Sorting        []*client_list_control_pb2.ClientSortControls `protobuf:"bytes,4,rep,name=sorting,proto3" json:"sorting,omitempty"`
}

func (x *ClientTransactionListRequest) Reset() {
	*x = ClientTransactionListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_client_transaction_pb2_client_transaction_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientTransactionListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientTransactionListRequest) ProtoMessage() {}

func (x *ClientTransactionListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_client_transaction_pb2_client_transaction_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientTransactionListRequest.ProtoReflect.Descriptor instead.
func (*ClientTransactionListRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_client_transaction_pb2_client_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *ClientTransactionListRequest) GetHeadId() string {
	if x != nil {
		return x.HeadId
	}
	return ""
}

func (x *ClientTransactionListRequest) GetTransactionIds() []string {
	if x != nil {
		return x.TransactionIds
	}
	return nil
}

func (x *ClientTransactionListRequest) GetPaging() *client_list_control_pb2.ClientPagingControls {
	if x != nil {
		return x.Paging
	}
	return nil
}

func (x *ClientTransactionListRequest) GetSorting() []*client_list_control_pb2.ClientSortControls {
	if x != nil {
		return x.Sorting
	}
	return nil
}

// A response that lists transactions from newest to oldest.
//
// Statuses:
//   * OK - everything worked as expected
//   * INTERNAL_ERROR - general error, such as protobuf failing to deserialize
//   * NOT_READY - the validator does not yet have a genesis block
//   * NO_ROOT - the head block specified was not found
//   * NO_RESOURCE - no txns were found with the parameters specified
//   * INVALID_PAGING - the paging controls were malformed or out of range
//   * INVALID_SORT - the sorting controls were malformed or invalid
type ClientTransactionListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status       ClientTransactionListResponse_Status          `protobuf:"varint,1,opt,name=status,proto3,enum=ClientTransactionListResponse_Status" json:"status,omitempty"`
	Transactions []*transaction_pb2.Transaction                `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	HeadId       string                                        `protobuf:"bytes,3,opt,name=head_id,json=headId,proto3" json:"head_id,omitempty"`
	Paging       *client_list_control_pb2.ClientPagingResponse `protobuf:"bytes,4,opt,name=paging,proto3" json:"paging,omitempty"`
}

func (x *ClientTransactionListResponse) Reset() {
	*x = ClientTransactionListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_client_transaction_pb2_client_transaction_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientTransactionListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientTransactionListResponse) ProtoMessage() {}

func (x *ClientTransactionListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_client_transaction_pb2_client_transaction_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientTransactionListResponse.ProtoReflect.Descriptor instead.
func (*ClientTransactionListResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_client_transaction_pb2_client_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *ClientTransactionListResponse) GetStatus() ClientTransactionListResponse_Status {
	if x != nil {
		return x.Status
	}
	return ClientTransactionListResponse_STATUS_UNSET
}

func (x *ClientTransactionListResponse) GetTransactions() []*transaction_pb2.Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ClientTransactionListResponse) GetHeadId() string {
	if x != nil {
		return x.HeadId
	}
	return ""
}

func (x *ClientTransactionListResponse) GetPaging() *client_list_control_pb2.ClientPagingResponse {
	if x != nil {
		return x.Paging
	}
	return nil
}

// Fetches a specific txn by its id (header_signature) from the blockchain.
type ClientTransactionGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TransactionId string `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
}

func (x *ClientTransactionGetRequest) Reset() {
	*x = ClientTransactionGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_client_transaction_pb2_client_transaction_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientTransactionGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientTransactionGetRequest) ProtoMessage() {}

func (x *ClientTransactionGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_client_transaction_pb2_client_transaction_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientTransactionGetRequest.ProtoReflect.Descriptor instead.
func (*ClientTransactionGetRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_client_transaction_pb2_client_transaction_proto_rawDescGZIP(), []int{2}
}

func (x *ClientTransactionGetRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

// A response that returns the txn specified by a ClientTransactionGetRequest.
//
// Statuses:
//   * OK - everything worked as expected, txn has been fetched
//   * INTERNAL_ERROR - general error, such as protobuf failing to deserialize
//   * NO_RESOURCE - no txn with the specified id exists
type ClientTransactionGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status      ClientTransactionGetResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=ClientTransactionGetResponse_Status" json:"status,omitempty"`
	Transaction *transaction_pb2.Transaction        `protobuf:"bytes,2,opt,name=transaction,proto3" json:"transaction,omitempty"`
}

func (x *ClientTransactionGetResponse) Reset() {
	*x = ClientTransactionGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_client_transaction_pb2_client_transaction_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientTransactionGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientTransactionGetResponse) ProtoMessage() {}

func (x *ClientTransactionGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_client_transaction_pb2_client_transaction_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientTransactionGetResponse.ProtoReflect.Descriptor instead.
func (*ClientTransactionGetResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_client_transaction_pb2_client_transaction_proto_rawDescGZIP(), []int{3}
}

func (x *ClientTransactionGetResponse) GetStatus() ClientTransactionGetResponse_Status {
	if x != nil {
		return x.Status
	}
	return ClientTransactionGetResponse_STATUS_UNSET
}

func (x *ClientTransactionGetResponse) GetTransaction() *transaction_pb2.Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

var File_protobuf_client_transaction_pb2_client_transaction_proto protoreflect.FileDescriptor

var file_protobuf_client_transaction_pb2_client_transaction_proto_rawDesc = []byte{
	0x0a, 0x38, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x62,
	0x32, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2a, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x5f, 0x70, 0x62, 0x32, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x3a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x70, 0x62, 0x32, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0xbe, 0x01, 0x0a, 0x1c, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x49, 0x64, 0x12, 0x27, 0x0a, 0x0f,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x73, 0x12, 0x2d, 0x0a, 0x06, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x61,
	0x67, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x73, 0x52, 0x06, 0x70, 0x61,
	0x67, 0x69, 0x6e, 0x67, 0x12, 0x2d, 0x0a, 0x07, 0x73, 0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x6f,
	0x72, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x73, 0x52, 0x07, 0x73, 0x6f, 0x72, 0x74,
	0x69, 0x6e, 0x67, 0x22, 0xf4, 0x02, 0x0a, 0x1d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x25, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x30, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x54, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x17, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x49, 0x64, 0x12,
	0x2d, 0x0a, 0x06, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x15, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x06, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x22, 0x99,
	0x01, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x45, 0x54, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x4f,
	0x4b, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f, 0x54, 0x5f, 0x52,
	0x45, 0x41, 0x44, 0x59, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x4e, 0x4f, 0x5f, 0x52, 0x4f, 0x4f,
	0x54, 0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b, 0x4e, 0x4f, 0x5f, 0x52, 0x45, 0x53, 0x4f, 0x55, 0x52,
	0x43, 0x45, 0x10, 0x05, 0x12, 0x12, 0x0a, 0x0e, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f,
	0x50, 0x41, 0x47, 0x49, 0x4e, 0x47, 0x10, 0x06, 0x12, 0x10, 0x0a, 0x0c, 0x49, 0x4e, 0x56, 0x41,
	0x4c, 0x49, 0x44, 0x5f, 0x53, 0x4f, 0x52, 0x54, 0x10, 0x07, 0x12, 0x0e, 0x0a, 0x0a, 0x49, 0x4e,
	0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x49, 0x44, 0x10, 0x08, 0x22, 0x44, 0x0a, 0x1b, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x47,
	0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64,
	0x22, 0xe5, 0x01, 0x0a, 0x1c, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x24, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x2e, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x57, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x54, 0x41,
	0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x45, 0x54, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x4f,
	0x4b, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f,
	0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x4e, 0x4f, 0x5f, 0x52, 0x45,
	0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x10, 0x05, 0x12, 0x0e, 0x0a, 0x0a, 0x49, 0x4e, 0x56, 0x41,
	0x4c, 0x49, 0x44, 0x5f, 0x49, 0x44, 0x10, 0x08, 0x42, 0x31, 0x0a, 0x15, 0x73, 0x61, 0x77, 0x74,
	0x6f, 0x6f, 0x74, 0x68, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x50, 0x01, 0x5a, 0x16, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x72, 0x61, 0x6e,
	0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x62, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_protobuf_client_transaction_pb2_client_transaction_proto_rawDescOnce sync.Once
	file_protobuf_client_transaction_pb2_client_transaction_proto_rawDescData = file_protobuf_client_transaction_pb2_client_transaction_proto_rawDesc
)

func file_protobuf_client_transaction_pb2_client_transaction_proto_rawDescGZIP() []byte {
	file_protobuf_client_transaction_pb2_client_transaction_proto_rawDescOnce.Do(func() {
		file_protobuf_client_transaction_pb2_client_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_client_transaction_pb2_client_transaction_proto_rawDescData)
	})
	return file_protobuf_client_transaction_pb2_client_transaction_proto_rawDescData
}

var file_protobuf_client_transaction_pb2_client_transaction_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protobuf_client_transaction_pb2_client_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protobuf_client_transaction_pb2_client_transaction_proto_goTypes = []interface{}{
	(ClientTransactionListResponse_Status)(0),            // 0: ClientTransactionListResponse.Status
	(ClientTransactionGetResponse_Status)(0),             // 1: ClientTransactionGetResponse.Status
	(*ClientTransactionListRequest)(nil),                 // 2: ClientTransactionListRequest
	(*ClientTransactionListResponse)(nil),                // 3: ClientTransactionListResponse
	(*ClientTransactionGetRequest)(nil),                  // 4: ClientTransactionGetRequest
	(*ClientTransactionGetResponse)(nil),                 // 5: ClientTransactionGetResponse
	(*client_list_control_pb2.ClientPagingControls)(nil), // 6: ClientPagingControls
	(*client_list_control_pb2.ClientSortControls)(nil),   // 7: ClientSortControls
	(*transaction_pb2.Transaction)(nil),                  // 8: Transaction
	(*client_list_control_pb2.ClientPagingResponse)(nil), // 9: ClientPagingResponse
}
var file_protobuf_client_transaction_pb2_client_transaction_proto_depIdxs = []int32{
	6, // 0: ClientTransactionListRequest.paging:type_name -> ClientPagingControls
	7, // 1: ClientTransactionListRequest.sorting:type_name -> ClientSortControls
	0, // 2: ClientTransactionListResponse.status:type_name -> ClientTransactionListResponse.Status
	8, // 3: ClientTransactionListResponse.transactions:type_name -> Transaction
	9, // 4: ClientTransactionListResponse.paging:type_name -> ClientPagingResponse
	1, // 5: ClientTransactionGetResponse.status:type_name -> ClientTransactionGetResponse.Status
	8, // 6: ClientTransactionGetResponse.transaction:type_name -> Transaction
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_protobuf_client_transaction_pb2_client_transaction_proto_init() }
func file_protobuf_client_transaction_pb2_client_transaction_proto_init() {
	if File_protobuf_client_transaction_pb2_client_transaction_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_client_transaction_pb2_client_transaction_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientTransactionListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_client_transaction_pb2_client_transaction_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientTransactionListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_client_transaction_pb2_client_transaction_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientTransactionGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_client_transaction_pb2_client_transaction_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientTransactionGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_client_transaction_pb2_client_transaction_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_client_transaction_pb2_client_transaction_proto_goTypes,
		DependencyIndexes: file_protobuf_client_transaction_pb2_client_transaction_proto_depIdxs,
		EnumInfos:         file_protobuf_client_transaction_pb2_client_transaction_proto_enumTypes,
		MessageInfos:      file_protobuf_client_transaction_pb2_client_transaction_proto_msgTypes,
	}.Build()
	File_protobuf_client_transaction_pb2_client_transaction_proto = out.File
	file_protobuf_client_transaction_pb2_client_transaction_proto_rawDesc = nil
	file_protobuf_client_transaction_pb2_client_transaction_proto_goTypes = nil
	file_protobuf_client_transaction_pb2_client_transaction_proto_depIdxs = nil
}
