// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/block_pb2/block.proto

package block_pb2

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	batch_pb2 "protobuf/batch_pb2"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BlockHeader struct {
	// Block number in the chain
	BlockNum uint64 `protobuf:"varint,1,opt,name=block_num,json=blockNum,proto3" json:"block_num,omitempty"`
	// The header_signature of the previous block that was added to the chain.
	PreviousBlockId string `protobuf:"bytes,2,opt,name=previous_block_id,json=previousBlockId,proto3" json:"previous_block_id,omitempty"`
	// Public key for the component internal to the validator that
	// signed the BlockHeader
	SignerPublicKey string `protobuf:"bytes,3,opt,name=signer_public_key,json=signerPublicKey,proto3" json:"signer_public_key,omitempty"`
	// List of batch.header_signatures that match the order of batches
	// required for the block
	BatchIds []string `protobuf:"bytes,4,rep,name=batch_ids,json=batchIds,proto3" json:"batch_ids,omitempty"`
	// Bytes that are set and verified by the consensus algorithm used to
	// create and validate the block
	Consensus []byte `protobuf:"bytes,5,opt,name=consensus,proto3" json:"consensus,omitempty"`
	// The state_root_hash should match the final state_root after all
	// transactions in the batches have been applied, otherwise the block
	// is not valid
	StateRootHash        string   `protobuf:"bytes,6,opt,name=state_root_hash,json=stateRootHash,proto3" json:"state_root_hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHeader) Reset()         { *m = BlockHeader{} }
func (m *BlockHeader) String() string { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()    {}
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_44965cf1612e2b2e, []int{0}
}

func (m *BlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeader.Unmarshal(m, b)
}
func (m *BlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeader.Marshal(b, m, deterministic)
}
func (m *BlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeader.Merge(m, src)
}
func (m *BlockHeader) XXX_Size() int {
	return xxx_messageInfo_BlockHeader.Size(m)
}
func (m *BlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeader proto.InternalMessageInfo

func (m *BlockHeader) GetBlockNum() uint64 {
	if m != nil {
		return m.BlockNum
	}
	return 0
}

func (m *BlockHeader) GetPreviousBlockId() string {
	if m != nil {
		return m.PreviousBlockId
	}
	return ""
}

func (m *BlockHeader) GetSignerPublicKey() string {
	if m != nil {
		return m.SignerPublicKey
	}
	return ""
}

func (m *BlockHeader) GetBatchIds() []string {
	if m != nil {
		return m.BatchIds
	}
	return nil
}

func (m *BlockHeader) GetConsensus() []byte {
	if m != nil {
		return m.Consensus
	}
	return nil
}

func (m *BlockHeader) GetStateRootHash() string {
	if m != nil {
		return m.StateRootHash
	}
	return ""
}

type Block struct {
	// The serialized version of the BlockHeader
	Header []byte `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	// The signature derived from signing the header
	HeaderSignature string `protobuf:"bytes,2,opt,name=header_signature,json=headerSignature,proto3" json:"header_signature,omitempty"`
	// A list of batches. The batches may contain new batches that other
	// validators may not have received yet, or they will be all batches needed
	// for block validation when passed to the journal
	Batches              []*batch_pb2.Batch `protobuf:"bytes,3,rep,name=batches,proto3" json:"batches,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_44965cf1612e2b2e, []int{1}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetHeader() []byte {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetHeaderSignature() string {
	if m != nil {
		return m.HeaderSignature
	}
	return ""
}

func (m *Block) GetBatches() []*batch_pb2.Batch {
	if m != nil {
		return m.Batches
	}
	return nil
}

func init() {
	proto.RegisterType((*BlockHeader)(nil), "BlockHeader")
	proto.RegisterType((*Block)(nil), "Block")
}

func init() { proto.RegisterFile("protobuf/block_pb2/block.proto", fileDescriptor_44965cf1612e2b2e) }

var fileDescriptor_44965cf1612e2b2e = []byte{
	// 309 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x91, 0xd1, 0x4a, 0xf3, 0x40,
	0x10, 0x85, 0xc9, 0x9f, 0x36, 0x7f, 0xb3, 0xad, 0x54, 0x17, 0x94, 0x45, 0x45, 0x42, 0x11, 0x89,
	0x5e, 0x54, 0xa8, 0x6f, 0xd0, 0xab, 0x16, 0x41, 0xca, 0x7a, 0xe7, 0xcd, 0xb2, 0x49, 0xb6, 0x26,
	0x34, 0xcd, 0x86, 0x9d, 0x5d, 0xa5, 0x0f, 0xec, 0x7b, 0x48, 0x66, 0x1b, 0xf5, 0x6e, 0xe6, 0x3b,
	0x87, 0x99, 0x33, 0x0c, 0xb9, 0x69, 0x8d, 0xb6, 0x3a, 0x73, 0xdb, 0xc7, 0xac, 0xd6, 0xf9, 0x4e,
	0xb4, 0xd9, 0xc2, 0x57, 0x73, 0x14, 0x2e, 0xff, 0xe8, 0xd2, 0xe6, 0xa5, 0xd7, 0xbb, 0xca, 0xeb,
	0xb3, 0xaf, 0x80, 0x8c, 0x97, 0x9d, 0x7f, 0xa5, 0x64, 0xa1, 0x0c, 0xbd, 0x22, 0xb1, 0x1f, 0xd4,
	0xb8, 0x3d, 0x0b, 0x92, 0x20, 0x1d, 0xf0, 0x11, 0x82, 0x17, 0xb7, 0xa7, 0x0f, 0xe4, 0xac, 0x35,
	0xea, 0xa3, 0xd2, 0x0e, 0x84, 0x77, 0x55, 0x05, 0xfb, 0x97, 0x04, 0x69, 0xcc, 0xa7, 0xbd, 0x80,
	0xc3, 0xd6, 0x45, 0xe7, 0x85, 0xea, 0xbd, 0x51, 0x46, 0xb4, 0x2e, 0xab, 0xab, 0x5c, 0xec, 0xd4,
	0x81, 0x85, 0xde, 0xeb, 0x85, 0x0d, 0xf2, 0x67, 0x75, 0xc0, 0xa5, 0x98, 0xae, 0x2a, 0x80, 0x0d,
	0x92, 0x30, 0x8d, 0xf9, 0x08, 0xc1, 0xba, 0x00, 0x7a, 0x4d, 0xe2, 0x5c, 0x37, 0xa0, 0x1a, 0x70,
	0xc0, 0x86, 0x49, 0x90, 0x4e, 0xf8, 0x2f, 0xa0, 0x77, 0x64, 0x0a, 0x56, 0x5a, 0x25, 0x8c, 0xd6,
	0x56, 0x94, 0x12, 0x4a, 0x16, 0xe1, 0x92, 0x13, 0xc4, 0x5c, 0x6b, 0xbb, 0x92, 0x50, 0xce, 0x6a,
	0x32, 0xc4, 0x64, 0xf4, 0x82, 0x44, 0x25, 0x9e, 0x8a, 0xd7, 0x4d, 0xf8, 0xb1, 0xa3, 0xf7, 0xe4,
	0xd4, 0x57, 0xa2, 0x4b, 0x27, 0xad, 0x33, 0xaa, 0x3f, 0xcd, 0xf3, 0xd7, 0x1e, 0xd3, 0x84, 0xfc,
	0xc7, 0x74, 0x0a, 0x58, 0x98, 0x84, 0xe9, 0x78, 0x11, 0xcd, 0x97, 0x5d, 0xcf, 0x7b, 0xbc, 0xbc,
	0x25, 0xe7, 0x20, 0x3f, 0xad, 0xd6, 0xb6, 0x9c, 0x43, 0x71, 0xfc, 0x45, 0xe6, 0xb6, 0x9b, 0xe0,
	0x2d, 0xfe, 0xf9, 0x53, 0x16, 0x21, 0x7e, 0xfa, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x89, 0x38, 0x39,
	0xd6, 0xc4, 0x01, 0x00, 0x00,
}
