// Copyright 2017 Intel Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// -----------------------------------------------------------------------------

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: protobuf/client_state_pb2/client_state.proto

package client_state_pb2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	client_list_control_pb2 "github.com/hyperledger/sawtooth-sdk-go/protobuf/client_list_control_pb2"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientStateListResponse_Status int32

const (
	ClientStateListResponse_STATUS_UNSET    ClientStateListResponse_Status = 0
	ClientStateListResponse_OK              ClientStateListResponse_Status = 1
	ClientStateListResponse_INTERNAL_ERROR  ClientStateListResponse_Status = 2
	ClientStateListResponse_NOT_READY       ClientStateListResponse_Status = 3
	ClientStateListResponse_NO_ROOT         ClientStateListResponse_Status = 4
	ClientStateListResponse_NO_RESOURCE     ClientStateListResponse_Status = 5
	ClientStateListResponse_INVALID_PAGING  ClientStateListResponse_Status = 6
	ClientStateListResponse_INVALID_SORT    ClientStateListResponse_Status = 7
	ClientStateListResponse_INVALID_ADDRESS ClientStateListResponse_Status = 8
	ClientStateListResponse_INVALID_ROOT    ClientStateListResponse_Status = 9
)

// Enum value maps for ClientStateListResponse_Status.
var (
	ClientStateListResponse_Status_name = map[int32]string{
		0: "STATUS_UNSET",
		1: "OK",
		2: "INTERNAL_ERROR",
		3: "NOT_READY",
		4: "NO_ROOT",
		5: "NO_RESOURCE",
		6: "INVALID_PAGING",
		7: "INVALID_SORT",
		8: "INVALID_ADDRESS",
		9: "INVALID_ROOT",
	}
	ClientStateListResponse_Status_value = map[string]int32{
		"STATUS_UNSET":    0,
		"OK":              1,
		"INTERNAL_ERROR":  2,
		"NOT_READY":       3,
		"NO_ROOT":         4,
		"NO_RESOURCE":     5,
		"INVALID_PAGING":  6,
		"INVALID_SORT":    7,
		"INVALID_ADDRESS": 8,
		"INVALID_ROOT":    9,
	}
)

func (x ClientStateListResponse_Status) Enum() *ClientStateListResponse_Status {
	p := new(ClientStateListResponse_Status)
	*p = x
	return p
}

func (x ClientStateListResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientStateListResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_client_state_pb2_client_state_proto_enumTypes[0].Descriptor()
}

func (ClientStateListResponse_Status) Type() protoreflect.EnumType {
	return &file_protobuf_client_state_pb2_client_state_proto_enumTypes[0]
}

func (x ClientStateListResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientStateListResponse_Status.Descriptor instead.
func (ClientStateListResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_client_state_pb2_client_state_proto_rawDescGZIP(), []int{1, 0}
}

type ClientStateGetResponse_Status int32

const (
	ClientStateGetResponse_STATUS_UNSET    ClientStateGetResponse_Status = 0
	ClientStateGetResponse_OK              ClientStateGetResponse_Status = 1
	ClientStateGetResponse_INTERNAL_ERROR  ClientStateGetResponse_Status = 2
	ClientStateGetResponse_NOT_READY       ClientStateGetResponse_Status = 3
	ClientStateGetResponse_NO_ROOT         ClientStateGetResponse_Status = 4
	ClientStateGetResponse_NO_RESOURCE     ClientStateGetResponse_Status = 5
	ClientStateGetResponse_INVALID_ADDRESS ClientStateGetResponse_Status = 6
	ClientStateGetResponse_INVALID_ROOT    ClientStateGetResponse_Status = 7
)

// Enum value maps for ClientStateGetResponse_Status.
var (
	ClientStateGetResponse_Status_name = map[int32]string{
		0: "STATUS_UNSET",
		1: "OK",
		2: "INTERNAL_ERROR",
		3: "NOT_READY",
		4: "NO_ROOT",
		5: "NO_RESOURCE",
		6: "INVALID_ADDRESS",
		7: "INVALID_ROOT",
	}
	ClientStateGetResponse_Status_value = map[string]int32{
		"STATUS_UNSET":    0,
		"OK":              1,
		"INTERNAL_ERROR":  2,
		"NOT_READY":       3,
		"NO_ROOT":         4,
		"NO_RESOURCE":     5,
		"INVALID_ADDRESS": 6,
		"INVALID_ROOT":    7,
	}
)

func (x ClientStateGetResponse_Status) Enum() *ClientStateGetResponse_Status {
	p := new(ClientStateGetResponse_Status)
	*p = x
	return p
}

func (x ClientStateGetResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ClientStateGetResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_client_state_pb2_client_state_proto_enumTypes[1].Descriptor()
}

func (ClientStateGetResponse_Status) Type() protoreflect.EnumType {
	return &file_protobuf_client_state_pb2_client_state_proto_enumTypes[1]
}

func (x ClientStateGetResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ClientStateGetResponse_Status.Descriptor instead.
func (ClientStateGetResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_client_state_pb2_client_state_proto_rawDescGZIP(), []int{3, 0}
}

// A request to list every entry in global state. Defaults to the most current
// tree, but can fetch older state by specifying a state root. Results can be
// further filtered by specifying a subtree with a partial address.
type ClientStateListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StateRoot string                                        `protobuf:"bytes,1,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	Address   string                                        `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Paging    *client_list_control_pb2.ClientPagingControls `protobuf:"bytes,4,opt,name=paging,proto3" json:"paging,omitempty"`
	Sorting   []*client_list_control_pb2.ClientSortControls `protobuf:"bytes,5,rep,name=sorting,proto3" json:"sorting,omitempty"`
}

func (x *ClientStateListRequest) Reset() {
	*x = ClientStateListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_client_state_pb2_client_state_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientStateListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStateListRequest) ProtoMessage() {}

func (x *ClientStateListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_client_state_pb2_client_state_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStateListRequest.ProtoReflect.Descriptor instead.
func (*ClientStateListRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_client_state_pb2_client_state_proto_rawDescGZIP(), []int{0}
}

func (x *ClientStateListRequest) GetStateRoot() string {
	if x != nil {
		return x.StateRoot
	}
	return ""
}

func (x *ClientStateListRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ClientStateListRequest) GetPaging() *client_list_control_pb2.ClientPagingControls {
	if x != nil {
		return x.Paging
	}
	return nil
}

func (x *ClientStateListRequest) GetSorting() []*client_list_control_pb2.ClientSortControls {
	if x != nil {
		return x.Sorting
	}
	return nil
}

type ClientStateListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    ClientStateListResponse_Status                `protobuf:"varint,1,opt,name=status,proto3,enum=ClientStateListResponse_Status" json:"status,omitempty"`
	Entries   []*ClientStateListResponse_Entry              `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	StateRoot string                                        `protobuf:"bytes,3,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	Paging    *client_list_control_pb2.ClientPagingResponse `protobuf:"bytes,4,opt,name=paging,proto3" json:"paging,omitempty"`
}

func (x *ClientStateListResponse) Reset() {
	*x = ClientStateListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_client_state_pb2_client_state_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientStateListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStateListResponse) ProtoMessage() {}

func (x *ClientStateListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_client_state_pb2_client_state_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStateListResponse.ProtoReflect.Descriptor instead.
func (*ClientStateListResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_client_state_pb2_client_state_proto_rawDescGZIP(), []int{1}
}

func (x *ClientStateListResponse) GetStatus() ClientStateListResponse_Status {
	if x != nil {
		return x.Status
	}
	return ClientStateListResponse_STATUS_UNSET
}

func (x *ClientStateListResponse) GetEntries() []*ClientStateListResponse_Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ClientStateListResponse) GetStateRoot() string {
	if x != nil {
		return x.StateRoot
	}
	return ""
}

func (x *ClientStateListResponse) GetPaging() *client_list_control_pb2.ClientPagingResponse {
	if x != nil {
		return x.Paging
	}
	return nil
}

// A request from a client for a particular entry in global state.
// Like State List, it defaults to the newest state, but a state root
// can be used to specify older data. Unlike State List the request must be
// provided with a full address that corresponds to a single entry.
type ClientStateGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StateRoot string `protobuf:"bytes,1,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	Address   string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *ClientStateGetRequest) Reset() {
	*x = ClientStateGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_client_state_pb2_client_state_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientStateGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStateGetRequest) ProtoMessage() {}

func (x *ClientStateGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_client_state_pb2_client_state_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStateGetRequest.ProtoReflect.Descriptor instead.
func (*ClientStateGetRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_client_state_pb2_client_state_proto_rawDescGZIP(), []int{2}
}

func (x *ClientStateGetRequest) GetStateRoot() string {
	if x != nil {
		return x.StateRoot
	}
	return ""
}

func (x *ClientStateGetRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// The response to a State Get Request from the client. Sends back just
// the data stored at the entry, not the address. Also sends back the
// head block id used to facilitate further requests.
//
// Statuses:
//   * OK - everything worked as expected
//   * INTERNAL_ERROR - general error, such as protobuf failing to deserialize
//   * NOT_READY - the validator does not yet have a genesis block
//   * NO_ROOT - the state_root specified was not found
//   * NO_RESOURCE - the address specified doesn't exist
//   * INVALID_ADDRESS - address isn't a valid, i.e. it's a subtree (truncated)
type ClientStateGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status    ClientStateGetResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=ClientStateGetResponse_Status" json:"status,omitempty"`
	Value     []byte                        `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	StateRoot string                        `protobuf:"bytes,3,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
}

func (x *ClientStateGetResponse) Reset() {
	*x = ClientStateGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_client_state_pb2_client_state_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientStateGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStateGetResponse) ProtoMessage() {}

func (x *ClientStateGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_client_state_pb2_client_state_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStateGetResponse.ProtoReflect.Descriptor instead.
func (*ClientStateGetResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_client_state_pb2_client_state_proto_rawDescGZIP(), []int{3}
}

func (x *ClientStateGetResponse) GetStatus() ClientStateGetResponse_Status {
	if x != nil {
		return x.Status
	}
	return ClientStateGetResponse_STATUS_UNSET
}

func (x *ClientStateGetResponse) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ClientStateGetResponse) GetStateRoot() string {
	if x != nil {
		return x.StateRoot
	}
	return ""
}

// An entry in the State
type ClientStateListResponse_Entry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Data    []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ClientStateListResponse_Entry) Reset() {
	*x = ClientStateListResponse_Entry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_client_state_pb2_client_state_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientStateListResponse_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientStateListResponse_Entry) ProtoMessage() {}

func (x *ClientStateListResponse_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_client_state_pb2_client_state_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientStateListResponse_Entry.ProtoReflect.Descriptor instead.
func (*ClientStateListResponse_Entry) Descriptor() ([]byte, []int) {
	return file_protobuf_client_state_pb2_client_state_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ClientStateListResponse_Entry) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ClientStateListResponse_Entry) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_protobuf_client_state_pb2_client_state_proto protoreflect.FileDescriptor

var file_protobuf_client_state_pb2_client_state_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x70, 0x62, 0x32, 0x2f, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x3a,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f,
	0x6c, 0x69, 0x73, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x5f, 0x70, 0x62, 0x32,
	0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x5f, 0x63, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xaf, 0x01, 0x0a, 0x16, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x72,
	0x6f, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65,
	0x52, 0x6f, 0x6f, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x2d,
	0x0a, 0x06, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x6e,
	0x74, 0x72, 0x6f, 0x6c, 0x73, 0x52, 0x06, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x12, 0x2d, 0x0a,
	0x07, 0x73, 0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x6f, 0x72, 0x74, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x73, 0x52, 0x07, 0x73, 0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x22, 0xc4, 0x03, 0x0a,
	0x17, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x38, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x12, 0x2d, 0x0a, 0x06, 0x70, 0x61,
	0x67, 0x69, 0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x50, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x52, 0x06, 0x70, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x1a, 0x35, 0x0a, 0x05, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0xb0, 0x01, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x0c, 0x53,
	0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x45, 0x54, 0x10, 0x00, 0x12, 0x06, 0x0a,
	0x02, 0x4f, 0x4b, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41,
	0x4c, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f, 0x54,
	0x5f, 0x52, 0x45, 0x41, 0x44, 0x59, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x4e, 0x4f, 0x5f, 0x52,
	0x4f, 0x4f, 0x54, 0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b, 0x4e, 0x4f, 0x5f, 0x52, 0x45, 0x53, 0x4f,
	0x55, 0x52, 0x43, 0x45, 0x10, 0x05, 0x12, 0x12, 0x0a, 0x0e, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49,
	0x44, 0x5f, 0x50, 0x41, 0x47, 0x49, 0x4e, 0x47, 0x10, 0x06, 0x12, 0x10, 0x0a, 0x0c, 0x49, 0x4e,
	0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x53, 0x4f, 0x52, 0x54, 0x10, 0x07, 0x12, 0x13, 0x0a, 0x0f,
	0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x41, 0x44, 0x44, 0x52, 0x45, 0x53, 0x53, 0x10,
	0x08, 0x12, 0x10, 0x0a, 0x0c, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x52, 0x4f, 0x4f,
	0x54, 0x10, 0x09, 0x22, 0x50, 0x0a, 0x15, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x92, 0x02, 0x0a, 0x16, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x53, 0x74, 0x61, 0x74, 0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x36, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x1e, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x65, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x6f, 0x6f, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x73, 0x74, 0x61, 0x74, 0x65, 0x52, 0x6f, 0x6f, 0x74, 0x22, 0x8a, 0x01,
	0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x54, 0x41, 0x54,
	0x55, 0x53, 0x5f, 0x55, 0x4e, 0x53, 0x45, 0x54, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b,
	0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x49, 0x4e, 0x54, 0x45, 0x52, 0x4e, 0x41, 0x4c, 0x5f, 0x45,
	0x52, 0x52, 0x4f, 0x52, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x4e, 0x4f, 0x54, 0x5f, 0x52, 0x45,
	0x41, 0x44, 0x59, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x4e, 0x4f, 0x5f, 0x52, 0x4f, 0x4f, 0x54,
	0x10, 0x04, 0x12, 0x0f, 0x0a, 0x0b, 0x4e, 0x4f, 0x5f, 0x52, 0x45, 0x53, 0x4f, 0x55, 0x52, 0x43,
	0x45, 0x10, 0x05, 0x12, 0x13, 0x0a, 0x0f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x41,
	0x44, 0x44, 0x52, 0x45, 0x53, 0x53, 0x10, 0x06, 0x12, 0x10, 0x0a, 0x0c, 0x49, 0x4e, 0x56, 0x41,
	0x4c, 0x49, 0x44, 0x5f, 0x52, 0x4f, 0x4f, 0x54, 0x10, 0x07, 0x42, 0x2b, 0x0a, 0x15, 0x73, 0x61,
	0x77, 0x74, 0x6f, 0x6f, 0x74, 0x68, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x50, 0x01, 0x5a, 0x10, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x5f, 0x70, 0x62, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_client_state_pb2_client_state_proto_rawDescOnce sync.Once
	file_protobuf_client_state_pb2_client_state_proto_rawDescData = file_protobuf_client_state_pb2_client_state_proto_rawDesc
)

func file_protobuf_client_state_pb2_client_state_proto_rawDescGZIP() []byte {
	file_protobuf_client_state_pb2_client_state_proto_rawDescOnce.Do(func() {
		file_protobuf_client_state_pb2_client_state_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_client_state_pb2_client_state_proto_rawDescData)
	})
	return file_protobuf_client_state_pb2_client_state_proto_rawDescData
}

var file_protobuf_client_state_pb2_client_state_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protobuf_client_state_pb2_client_state_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protobuf_client_state_pb2_client_state_proto_goTypes = []interface{}{
	(ClientStateListResponse_Status)(0),                  // 0: ClientStateListResponse.Status
	(ClientStateGetResponse_Status)(0),                   // 1: ClientStateGetResponse.Status
	(*ClientStateListRequest)(nil),                       // 2: ClientStateListRequest
	(*ClientStateListResponse)(nil),                      // 3: ClientStateListResponse
	(*ClientStateGetRequest)(nil),                        // 4: ClientStateGetRequest
	(*ClientStateGetResponse)(nil),                       // 5: ClientStateGetResponse
	(*ClientStateListResponse_Entry)(nil),                // 6: ClientStateListResponse.Entry
	(*client_list_control_pb2.ClientPagingControls)(nil), // 7: ClientPagingControls
	(*client_list_control_pb2.ClientSortControls)(nil),   // 8: ClientSortControls
	(*client_list_control_pb2.ClientPagingResponse)(nil), // 9: ClientPagingResponse
}
var file_protobuf_client_state_pb2_client_state_proto_depIdxs = []int32{
	7, // 0: ClientStateListRequest.paging:type_name -> ClientPagingControls
	8, // 1: ClientStateListRequest.sorting:type_name -> ClientSortControls
	0, // 2: ClientStateListResponse.status:type_name -> ClientStateListResponse.Status
	6, // 3: ClientStateListResponse.entries:type_name -> ClientStateListResponse.Entry
	9, // 4: ClientStateListResponse.paging:type_name -> ClientPagingResponse
	1, // 5: ClientStateGetResponse.status:type_name -> ClientStateGetResponse.Status
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_protobuf_client_state_pb2_client_state_proto_init() }
func file_protobuf_client_state_pb2_client_state_proto_init() {
	if File_protobuf_client_state_pb2_client_state_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_client_state_pb2_client_state_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientStateListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_client_state_pb2_client_state_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientStateListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_client_state_pb2_client_state_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientStateGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_client_state_pb2_client_state_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientStateGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_client_state_pb2_client_state_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientStateListResponse_Entry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_client_state_pb2_client_state_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_client_state_pb2_client_state_proto_goTypes,
		DependencyIndexes: file_protobuf_client_state_pb2_client_state_proto_depIdxs,
		EnumInfos:         file_protobuf_client_state_pb2_client_state_proto_enumTypes,
		MessageInfos:      file_protobuf_client_state_pb2_client_state_proto_msgTypes,
	}.Build()
	File_protobuf_client_state_pb2_client_state_proto = out.File
	file_protobuf_client_state_pb2_client_state_proto_rawDesc = nil
	file_protobuf_client_state_pb2_client_state_proto_goTypes = nil
	file_protobuf_client_state_pb2_client_state_proto_depIdxs = nil
}
