// Copyright 2017 Intel Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// -----------------------------------------------------------------------------

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: protobuf/setting_pb2/setting.proto

package setting_pb2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Setting Container for on-chain configuration key/value pairs
type Setting struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// List of setting entries - more than one implies a state key collision
	Entries []*Setting_Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *Setting) Reset() {
	*x = Setting{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_setting_pb2_setting_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Setting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Setting) ProtoMessage() {}

func (x *Setting) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_setting_pb2_setting_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Setting.ProtoReflect.Descriptor instead.
func (*Setting) Descriptor() ([]byte, []int) {
	return file_protobuf_setting_pb2_setting_proto_rawDescGZIP(), []int{0}
}

func (x *Setting) GetEntries() []*Setting_Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// Contains a setting entry (or entries, in the case of collisions).
type Setting_Entry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Setting_Entry) Reset() {
	*x = Setting_Entry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_setting_pb2_setting_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Setting_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Setting_Entry) ProtoMessage() {}

func (x *Setting_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_setting_pb2_setting_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Setting_Entry.ProtoReflect.Descriptor instead.
func (*Setting_Entry) Descriptor() ([]byte, []int) {
	return file_protobuf_setting_pb2_setting_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Setting_Entry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Setting_Entry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_protobuf_setting_pb2_setting_proto protoreflect.FileDescriptor

var file_protobuf_setting_pb2_setting_proto_rawDesc = []byte{
	0x0a, 0x22, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x5f, 0x70, 0x62, 0x32, 0x2f, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x64, 0x0a, 0x07, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x12,
	0x28, 0x0a, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x0e, 0x2e, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x1a, 0x2f, 0x0a, 0x05, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x26, 0x0a, 0x15, 0x73, 0x61,
	0x77, 0x74, 0x6f, 0x6f, 0x74, 0x68, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x50, 0x01, 0x5a, 0x0b, 0x73, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x5f, 0x70,
	0x62, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_setting_pb2_setting_proto_rawDescOnce sync.Once
	file_protobuf_setting_pb2_setting_proto_rawDescData = file_protobuf_setting_pb2_setting_proto_rawDesc
)

func file_protobuf_setting_pb2_setting_proto_rawDescGZIP() []byte {
	file_protobuf_setting_pb2_setting_proto_rawDescOnce.Do(func() {
		file_protobuf_setting_pb2_setting_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_setting_pb2_setting_proto_rawDescData)
	})
	return file_protobuf_setting_pb2_setting_proto_rawDescData
}

var file_protobuf_setting_pb2_setting_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_setting_pb2_setting_proto_goTypes = []interface{}{
	(*Setting)(nil),       // 0: Setting
	(*Setting_Entry)(nil), // 1: Setting.Entry
}
var file_protobuf_setting_pb2_setting_proto_depIdxs = []int32{
	1, // 0: Setting.entries:type_name -> Setting.Entry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobuf_setting_pb2_setting_proto_init() }
func file_protobuf_setting_pb2_setting_proto_init() {
	if File_protobuf_setting_pb2_setting_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_setting_pb2_setting_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Setting); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_setting_pb2_setting_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Setting_Entry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_setting_pb2_setting_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_setting_pb2_setting_proto_goTypes,
		DependencyIndexes: file_protobuf_setting_pb2_setting_proto_depIdxs,
		MessageInfos:      file_protobuf_setting_pb2_setting_proto_msgTypes,
	}.Build()
	File_protobuf_setting_pb2_setting_proto = out.File
	file_protobuf_setting_pb2_setting_proto_rawDesc = nil
	file_protobuf_setting_pb2_setting_proto_goTypes = nil
	file_protobuf_setting_pb2_setting_proto_depIdxs = nil
}
