// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/client_receipt_pb2/client_receipt.proto

package client_receipt_pb2

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	transaction_receipt_pb2 "protobuf/transaction_receipt_pb2"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ClientReceiptGetResponse_Status int32

const (
	ClientReceiptGetResponse_STATUS_UNSET   ClientReceiptGetResponse_Status = 0
	ClientReceiptGetResponse_OK             ClientReceiptGetResponse_Status = 1
	ClientReceiptGetResponse_INTERNAL_ERROR ClientReceiptGetResponse_Status = 2
	ClientReceiptGetResponse_NO_RESOURCE    ClientReceiptGetResponse_Status = 5
	ClientReceiptGetResponse_INVALID_ID     ClientReceiptGetResponse_Status = 8
)

var ClientReceiptGetResponse_Status_name = map[int32]string{
	0: "STATUS_UNSET",
	1: "OK",
	2: "INTERNAL_ERROR",
	5: "NO_RESOURCE",
	8: "INVALID_ID",
}

var ClientReceiptGetResponse_Status_value = map[string]int32{
	"STATUS_UNSET":   0,
	"OK":             1,
	"INTERNAL_ERROR": 2,
	"NO_RESOURCE":    5,
	"INVALID_ID":     8,
}

func (x ClientReceiptGetResponse_Status) String() string {
	return proto.EnumName(ClientReceiptGetResponse_Status_name, int32(x))
}

func (ClientReceiptGetResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_149b4755ff14e46f, []int{1, 0}
}

// Fetches a specific txn by its id (header_signature) from the blockchain.
type ClientReceiptGetRequest struct {
	TransactionIds       []string `protobuf:"bytes,1,rep,name=transaction_ids,json=transactionIds,proto3" json:"transaction_ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientReceiptGetRequest) Reset()         { *m = ClientReceiptGetRequest{} }
func (m *ClientReceiptGetRequest) String() string { return proto.CompactTextString(m) }
func (*ClientReceiptGetRequest) ProtoMessage()    {}
func (*ClientReceiptGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_149b4755ff14e46f, []int{0}
}

func (m *ClientReceiptGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientReceiptGetRequest.Unmarshal(m, b)
}
func (m *ClientReceiptGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientReceiptGetRequest.Marshal(b, m, deterministic)
}
func (m *ClientReceiptGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientReceiptGetRequest.Merge(m, src)
}
func (m *ClientReceiptGetRequest) XXX_Size() int {
	return xxx_messageInfo_ClientReceiptGetRequest.Size(m)
}
func (m *ClientReceiptGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientReceiptGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClientReceiptGetRequest proto.InternalMessageInfo

func (m *ClientReceiptGetRequest) GetTransactionIds() []string {
	if m != nil {
		return m.TransactionIds
	}
	return nil
}

// A response that returns the txn receipt specified by a
// ClientTransactionReceiptGetRequest.
//
// Statuses:
//   * OK - everything worked as expected, txn receipt has been fetched
//   * INTERNAL_ERROR - general error, such as protobuf failing to deserialize
//   * NO_RESOURCE - no receipt exists for the transaction id specified
type ClientReceiptGetResponse struct {
	Status               ClientReceiptGetResponse_Status               `protobuf:"varint,1,opt,name=status,proto3,enum=ClientReceiptGetResponse_Status" json:"status,omitempty"`
	Receipts             []*transaction_receipt_pb2.TransactionReceipt `protobuf:"bytes,2,rep,name=receipts,proto3" json:"receipts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                      `json:"-"`
	XXX_unrecognized     []byte                                        `json:"-"`
	XXX_sizecache        int32                                         `json:"-"`
}

func (m *ClientReceiptGetResponse) Reset()         { *m = ClientReceiptGetResponse{} }
func (m *ClientReceiptGetResponse) String() string { return proto.CompactTextString(m) }
func (*ClientReceiptGetResponse) ProtoMessage()    {}
func (*ClientReceiptGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_149b4755ff14e46f, []int{1}
}

func (m *ClientReceiptGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientReceiptGetResponse.Unmarshal(m, b)
}
func (m *ClientReceiptGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientReceiptGetResponse.Marshal(b, m, deterministic)
}
func (m *ClientReceiptGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientReceiptGetResponse.Merge(m, src)
}
func (m *ClientReceiptGetResponse) XXX_Size() int {
	return xxx_messageInfo_ClientReceiptGetResponse.Size(m)
}
func (m *ClientReceiptGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientReceiptGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClientReceiptGetResponse proto.InternalMessageInfo

func (m *ClientReceiptGetResponse) GetStatus() ClientReceiptGetResponse_Status {
	if m != nil {
		return m.Status
	}
	return ClientReceiptGetResponse_STATUS_UNSET
}

func (m *ClientReceiptGetResponse) GetReceipts() []*transaction_receipt_pb2.TransactionReceipt {
	if m != nil {
		return m.Receipts
	}
	return nil
}

func init() {
	proto.RegisterEnum("ClientReceiptGetResponse_Status", ClientReceiptGetResponse_Status_name, ClientReceiptGetResponse_Status_value)
	proto.RegisterType((*ClientReceiptGetRequest)(nil), "ClientReceiptGetRequest")
	proto.RegisterType((*ClientReceiptGetResponse)(nil), "ClientReceiptGetResponse")
}

func init() {
	proto.RegisterFile("protobuf/client_receipt_pb2/client_receipt.proto", fileDescriptor_149b4755ff14e46f)
}

var fileDescriptor_149b4755ff14e46f = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0x86, 0xbf, 0xb4, 0x7c, 0xa1, 0x9e, 0x4a, 0x3a, 0x8c, 0x88, 0xc5, 0x55, 0xc9, 0xc6, 0x6c,
	0x9c, 0x4a, 0xdc, 0x88, 0xbb, 0xb4, 0x0d, 0x12, 0x2c, 0x89, 0x4c, 0x12, 0x05, 0x37, 0x43, 0x7e,
	0x46, 0x0c, 0x4a, 0x26, 0x66, 0x26, 0x78, 0xb7, 0x5e, 0x8b, 0x98, 0xc4, 0x5a, 0xad, 0x6e, 0xdf,
	0x79, 0x9e, 0x77, 0x0e, 0xe7, 0xc0, 0x59, 0x55, 0x0b, 0x25, 0xd2, 0xe6, 0x61, 0x9e, 0x3d, 0x17,
	0xbc, 0x54, 0xac, 0xe6, 0x19, 0x2f, 0x2a, 0xc5, 0xaa, 0xd4, 0xfe, 0x11, 0x91, 0x16, 0x3d, 0xbe,
	0xdc, 0x18, 0xaa, 0x4e, 0x4a, 0x99, 0x64, 0xaa, 0x10, 0xe5, 0x37, 0xed, 0x97, 0xbc, 0x73, 0xcd,
	0x05, 0x1c, 0x2d, 0xdb, 0x4e, 0xda, 0xc5, 0x57, 0x5c, 0x51, 0xfe, 0xd2, 0x70, 0xa9, 0xf0, 0x09,
	0x4c, 0xb6, 0xbd, 0x22, 0x97, 0x53, 0x6d, 0x36, 0xb4, 0xf6, 0xa8, 0xb1, 0x15, 0x7b, 0xb9, 0x34,
	0xdf, 0x34, 0x98, 0xee, 0x96, 0xc8, 0x4a, 0x94, 0x92, 0xe3, 0x0b, 0xd0, 0xa5, 0x4a, 0x54, 0xf3,
	0x21, 0x6b, 0x96, 0x61, 0xcf, 0xc8, 0x5f, 0x28, 0x09, 0x5b, 0x8e, 0xf6, 0x3c, 0x9e, 0xc3, 0xa8,
	0x9f, 0x55, 0x4e, 0x07, 0xb3, 0xa1, 0x35, 0xb6, 0x0f, 0x48, 0xf4, 0xf5, 0x73, 0x5f, 0x40, 0x37,
	0x90, 0x79, 0x07, 0x7a, 0x57, 0x81, 0x11, 0xec, 0x87, 0x91, 0x13, 0xc5, 0x21, 0x8b, 0xfd, 0xd0,
	0x8d, 0xd0, 0x3f, 0xac, 0xc3, 0x20, 0xb8, 0x46, 0x1a, 0xc6, 0x60, 0x78, 0x7e, 0xe4, 0x52, 0xdf,
	0x59, 0x33, 0x97, 0xd2, 0x80, 0xa2, 0x01, 0x9e, 0xc0, 0xd8, 0x0f, 0x18, 0x75, 0xc3, 0x20, 0xa6,
	0x4b, 0x17, 0xfd, 0xc7, 0x06, 0x80, 0xe7, 0xdf, 0x3a, 0x6b, 0x6f, 0xc5, 0xbc, 0x15, 0x1a, 0x2d,
	0x4e, 0xe1, 0x50, 0x26, 0xaf, 0x4a, 0x08, 0xf5, 0x48, 0x64, 0xfe, 0x44, 0x3e, 0xf7, 0x7d, 0xa3,
	0xdd, 0xe3, 0xdd, 0x23, 0xa5, 0x7a, 0xfb, 0x7e, 0xfe, 0x1e, 0x00, 0x00, 0xff, 0xff, 0xba, 0x64,
	0x96, 0x4b, 0xca, 0x01, 0x00, 0x00,
}
