// Copyright 2016, 2017 Intel Corporation
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// -----------------------------------------------------------------------------

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: protobuf/network_pb2/network.proto

package network_pb2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GossipMessage_ContentType int32

const (
	GossipMessage_CONTENT_TYPE_UNSET GossipMessage_ContentType = 0
	GossipMessage_BLOCK              GossipMessage_ContentType = 1
	GossipMessage_BATCH              GossipMessage_ContentType = 2
)

// Enum value maps for GossipMessage_ContentType.
var (
	GossipMessage_ContentType_name = map[int32]string{
		0: "CONTENT_TYPE_UNSET",
		1: "BLOCK",
		2: "BATCH",
	}
	GossipMessage_ContentType_value = map[string]int32{
		"CONTENT_TYPE_UNSET": 0,
		"BLOCK":              1,
		"BATCH":              2,
	}
)

func (x GossipMessage_ContentType) Enum() *GossipMessage_ContentType {
	p := new(GossipMessage_ContentType)
	*p = x
	return p
}

func (x GossipMessage_ContentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GossipMessage_ContentType) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_network_pb2_network_proto_enumTypes[0].Descriptor()
}

func (GossipMessage_ContentType) Type() protoreflect.EnumType {
	return &file_protobuf_network_pb2_network_proto_enumTypes[0]
}

func (x GossipMessage_ContentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GossipMessage_ContentType.Descriptor instead.
func (GossipMessage_ContentType) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_network_pb2_network_proto_rawDescGZIP(), []int{7, 0}
}

type NetworkAcknowledgement_Status int32

const (
	NetworkAcknowledgement_STATUS_UNSET NetworkAcknowledgement_Status = 0
	NetworkAcknowledgement_OK           NetworkAcknowledgement_Status = 1
	NetworkAcknowledgement_ERROR        NetworkAcknowledgement_Status = 2
)

// Enum value maps for NetworkAcknowledgement_Status.
var (
	NetworkAcknowledgement_Status_name = map[int32]string{
		0: "STATUS_UNSET",
		1: "OK",
		2: "ERROR",
	}
	NetworkAcknowledgement_Status_value = map[string]int32{
		"STATUS_UNSET": 0,
		"OK":           1,
		"ERROR":        2,
	}
)

func (x NetworkAcknowledgement_Status) Enum() *NetworkAcknowledgement_Status {
	p := new(NetworkAcknowledgement_Status)
	*p = x
	return p
}

func (x NetworkAcknowledgement_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkAcknowledgement_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_network_pb2_network_proto_enumTypes[1].Descriptor()
}

func (NetworkAcknowledgement_Status) Type() protoreflect.EnumType {
	return &file_protobuf_network_pb2_network_proto_enumTypes[1]
}

func (x NetworkAcknowledgement_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NetworkAcknowledgement_Status.Descriptor instead.
func (NetworkAcknowledgement_Status) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_network_pb2_network_proto_rawDescGZIP(), []int{8, 0}
}

// The disconnect message from a client to the server
type DisconnectMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DisconnectMessage) Reset() {
	*x = DisconnectMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_network_pb2_network_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisconnectMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectMessage) ProtoMessage() {}

func (x *DisconnectMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_network_pb2_network_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectMessage.ProtoReflect.Descriptor instead.
func (*DisconnectMessage) Descriptor() ([]byte, []int) {
	return file_protobuf_network_pb2_network_proto_rawDescGZIP(), []int{0}
}

// The registration request from a peer to the validator
type PeerRegisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Endpoint string `protobuf:"bytes,1,opt,name=endpoint,proto3" json:"endpoint,omitempty"`
	// The current version of the network protocol that is being used by the
	// sender.  This version is an increasing value.
	ProtocolVersion uint32 `protobuf:"varint,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
}

func (x *PeerRegisterRequest) Reset() {
	*x = PeerRegisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_network_pb2_network_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeerRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerRegisterRequest) ProtoMessage() {}

func (x *PeerRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_network_pb2_network_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerRegisterRequest.ProtoReflect.Descriptor instead.
func (*PeerRegisterRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_network_pb2_network_proto_rawDescGZIP(), []int{1}
}

func (x *PeerRegisterRequest) GetEndpoint() string {
	if x != nil {
		return x.Endpoint
	}
	return ""
}

func (x *PeerRegisterRequest) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

// The unregistration request from a peer to the validator
type PeerUnregisterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PeerUnregisterRequest) Reset() {
	*x = PeerUnregisterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_network_pb2_network_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PeerUnregisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerUnregisterRequest) ProtoMessage() {}

func (x *PeerUnregisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_network_pb2_network_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerUnregisterRequest.ProtoReflect.Descriptor instead.
func (*PeerUnregisterRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_network_pb2_network_proto_rawDescGZIP(), []int{2}
}

type GetPeersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetPeersRequest) Reset() {
	*x = GetPeersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_network_pb2_network_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeersRequest) ProtoMessage() {}

func (x *GetPeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_network_pb2_network_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeersRequest.ProtoReflect.Descriptor instead.
func (*GetPeersRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_network_pb2_network_proto_rawDescGZIP(), []int{3}
}

type GetPeersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PeerEndpoints []string `protobuf:"bytes,1,rep,name=peer_endpoints,json=peerEndpoints,proto3" json:"peer_endpoints,omitempty"`
}

func (x *GetPeersResponse) Reset() {
	*x = GetPeersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_network_pb2_network_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPeersResponse) ProtoMessage() {}

func (x *GetPeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_network_pb2_network_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPeersResponse.ProtoReflect.Descriptor instead.
func (*GetPeersResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_network_pb2_network_proto_rawDescGZIP(), []int{4}
}

func (x *GetPeersResponse) GetPeerEndpoints() []string {
	if x != nil {
		return x.PeerEndpoints
	}
	return nil
}

type PingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_network_pb2_network_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_network_pb2_network_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_network_pb2_network_proto_rawDescGZIP(), []int{5}
}

type PingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_network_pb2_network_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_network_pb2_network_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_network_pb2_network_proto_rawDescGZIP(), []int{6}
}

type GossipMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content     []byte                    `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	ContentType GossipMessage_ContentType `protobuf:"varint,2,opt,name=content_type,json=contentType,proto3,enum=GossipMessage_ContentType" json:"content_type,omitempty"`
	TimeToLive  uint32                    `protobuf:"varint,3,opt,name=time_to_live,json=timeToLive,proto3" json:"time_to_live,omitempty"`
}

func (x *GossipMessage) Reset() {
	*x = GossipMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_network_pb2_network_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GossipMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipMessage) ProtoMessage() {}

func (x *GossipMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_network_pb2_network_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipMessage.ProtoReflect.Descriptor instead.
func (*GossipMessage) Descriptor() ([]byte, []int) {
	return file_protobuf_network_pb2_network_proto_rawDescGZIP(), []int{7}
}

func (x *GossipMessage) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *GossipMessage) GetContentType() GossipMessage_ContentType {
	if x != nil {
		return x.ContentType
	}
	return GossipMessage_CONTENT_TYPE_UNSET
}

func (x *GossipMessage) GetTimeToLive() uint32 {
	if x != nil {
		return x.TimeToLive
	}
	return 0
}

// A response sent from the validator to the peer acknowledging message
// receipt
type NetworkAcknowledgement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status NetworkAcknowledgement_Status `protobuf:"varint,1,opt,name=status,proto3,enum=NetworkAcknowledgement_Status" json:"status,omitempty"`
}

func (x *NetworkAcknowledgement) Reset() {
	*x = NetworkAcknowledgement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_network_pb2_network_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkAcknowledgement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkAcknowledgement) ProtoMessage() {}

func (x *NetworkAcknowledgement) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_network_pb2_network_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkAcknowledgement.ProtoReflect.Descriptor instead.
func (*NetworkAcknowledgement) Descriptor() ([]byte, []int) {
	return file_protobuf_network_pb2_network_proto_rawDescGZIP(), []int{8}
}

func (x *NetworkAcknowledgement) GetStatus() NetworkAcknowledgement_Status {
	if x != nil {
		return x.Status
	}
	return NetworkAcknowledgement_STATUS_UNSET
}

type GossipBlockRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The id of the block that is being requested
	BlockId string `protobuf:"bytes,1,opt,name=block_id,json=blockId,proto3" json:"block_id,omitempty"`
	// A random string that provides uniqueness for requests with
	// otherwise identical fields.
	Nonce      string `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	TimeToLive uint32 `protobuf:"varint,3,opt,name=time_to_live,json=timeToLive,proto3" json:"time_to_live,omitempty"`
}

func (x *GossipBlockRequest) Reset() {
	*x = GossipBlockRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_network_pb2_network_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GossipBlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipBlockRequest) ProtoMessage() {}

func (x *GossipBlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_network_pb2_network_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipBlockRequest.ProtoReflect.Descriptor instead.
func (*GossipBlockRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_network_pb2_network_proto_rawDescGZIP(), []int{9}
}

func (x *GossipBlockRequest) GetBlockId() string {
	if x != nil {
		return x.BlockId
	}
	return ""
}

func (x *GossipBlockRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *GossipBlockRequest) GetTimeToLive() uint32 {
	if x != nil {
		return x.TimeToLive
	}
	return 0
}

type GossipBlockResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The block
	Content []byte `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *GossipBlockResponse) Reset() {
	*x = GossipBlockResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_network_pb2_network_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GossipBlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipBlockResponse) ProtoMessage() {}

func (x *GossipBlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_network_pb2_network_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipBlockResponse.ProtoReflect.Descriptor instead.
func (*GossipBlockResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_network_pb2_network_proto_rawDescGZIP(), []int{10}
}

func (x *GossipBlockResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type GossipBatchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//The batch
	Content []byte `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *GossipBatchResponse) Reset() {
	*x = GossipBatchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_network_pb2_network_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GossipBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipBatchResponse) ProtoMessage() {}

func (x *GossipBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_network_pb2_network_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipBatchResponse.ProtoReflect.Descriptor instead.
func (*GossipBatchResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_network_pb2_network_proto_rawDescGZIP(), []int{11}
}

func (x *GossipBatchResponse) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type GossipBatchByBatchIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The id of the batch that is being requested
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// A random string that provides uniqueness for requests with
	// otherwise identical fields.
	Nonce      string `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	TimeToLive uint32 `protobuf:"varint,3,opt,name=time_to_live,json=timeToLive,proto3" json:"time_to_live,omitempty"`
}

func (x *GossipBatchByBatchIdRequest) Reset() {
	*x = GossipBatchByBatchIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_network_pb2_network_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GossipBatchByBatchIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipBatchByBatchIdRequest) ProtoMessage() {}

func (x *GossipBatchByBatchIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_network_pb2_network_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipBatchByBatchIdRequest.ProtoReflect.Descriptor instead.
func (*GossipBatchByBatchIdRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_network_pb2_network_proto_rawDescGZIP(), []int{12}
}

func (x *GossipBatchByBatchIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GossipBatchByBatchIdRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *GossipBatchByBatchIdRequest) GetTimeToLive() uint32 {
	if x != nil {
		return x.TimeToLive
	}
	return 0
}

type GossipBatchByTransactionIdRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The id's of the transaction that are in the batches requested
	Ids []string `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	// A random string that provides uniqueness for requests with
	// otherwise identical fields.
	Nonce      string `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	TimeToLive uint32 `protobuf:"varint,3,opt,name=time_to_live,json=timeToLive,proto3" json:"time_to_live,omitempty"`
}

func (x *GossipBatchByTransactionIdRequest) Reset() {
	*x = GossipBatchByTransactionIdRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_network_pb2_network_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GossipBatchByTransactionIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipBatchByTransactionIdRequest) ProtoMessage() {}

func (x *GossipBatchByTransactionIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_network_pb2_network_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipBatchByTransactionIdRequest.ProtoReflect.Descriptor instead.
func (*GossipBatchByTransactionIdRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_network_pb2_network_proto_rawDescGZIP(), []int{13}
}

func (x *GossipBatchByTransactionIdRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *GossipBatchByTransactionIdRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *GossipBatchByTransactionIdRequest) GetTimeToLive() uint32 {
	if x != nil {
		return x.TimeToLive
	}
	return 0
}

type GossipConsensusMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message    []byte `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	SenderId   []byte `protobuf:"bytes,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	TimeToLive uint32 `protobuf:"varint,3,opt,name=time_to_live,json=timeToLive,proto3" json:"time_to_live,omitempty"`
}

func (x *GossipConsensusMessage) Reset() {
	*x = GossipConsensusMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_network_pb2_network_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GossipConsensusMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GossipConsensusMessage) ProtoMessage() {}

func (x *GossipConsensusMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_network_pb2_network_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GossipConsensusMessage.ProtoReflect.Descriptor instead.
func (*GossipConsensusMessage) Descriptor() ([]byte, []int) {
	return file_protobuf_network_pb2_network_proto_rawDescGZIP(), []int{14}
}

func (x *GossipConsensusMessage) GetMessage() []byte {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *GossipConsensusMessage) GetSenderId() []byte {
	if x != nil {
		return x.SenderId
	}
	return nil
}

func (x *GossipConsensusMessage) GetTimeToLive() uint32 {
	if x != nil {
		return x.TimeToLive
	}
	return 0
}

var File_protobuf_network_pb2_network_proto protoreflect.FileDescriptor

var file_protobuf_network_pb2_network_proto_rawDesc = []byte{
	0x0a, 0x22, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x5f, 0x70, 0x62, 0x32, 0x2f, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x13, 0x0a, 0x11, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x5c, 0x0a, 0x13, 0x50, 0x65, 0x65,
	0x72, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x29, 0x0a, 0x10,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x17, 0x0a, 0x15, 0x50, 0x65, 0x65, 0x72, 0x55,
	0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x11, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x50, 0x65, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x22, 0x39, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x50, 0x65, 0x65, 0x72, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x65, 0x65, 0x72, 0x5f,
	0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0d, 0x70, 0x65, 0x65, 0x72, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x22, 0x0d,
	0x0a, 0x0b, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a,
	0x0c, 0x50, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xc7, 0x01,
	0x0a, 0x0d, 0x47, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x3d, 0x0a, 0x0c, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32,
	0x1a, 0x2e, 0x47, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0c, 0x74, 0x69, 0x6d, 0x65,
	0x5f, 0x74, 0x6f, 0x5f, 0x6c, 0x69, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a,
	0x74, 0x69, 0x6d, 0x65, 0x54, 0x6f, 0x4c, 0x69, 0x76, 0x65, 0x22, 0x3b, 0x0a, 0x0b, 0x43, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x12, 0x43, 0x4f, 0x4e,
	0x54, 0x45, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x45, 0x54, 0x10,
	0x00, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x4c, 0x4f, 0x43, 0x4b, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05,
	0x42, 0x41, 0x54, 0x43, 0x48, 0x10, 0x02, 0x22, 0x7f, 0x0a, 0x16, 0x4e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x41, 0x63, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x36, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1e, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x41, 0x63, 0x6b, 0x6e, 0x6f,
	0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2d, 0x0a, 0x06, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x55, 0x4e,
	0x53, 0x45, 0x54, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x01, 0x12, 0x09, 0x0a,
	0x05, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x02, 0x22, 0x67, 0x0a, 0x12, 0x47, 0x6f, 0x73, 0x73,
	0x69, 0x70, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19,
	0x0a, 0x08, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e,
	0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12,
	0x20, 0x0a, 0x0c, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x74, 0x6f, 0x5f, 0x6c, 0x69, 0x76, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x54, 0x6f, 0x4c, 0x69, 0x76,
	0x65, 0x22, 0x2f, 0x0a, 0x13, 0x47, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x22, 0x2f, 0x0a, 0x13, 0x47, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x42, 0x61, 0x74, 0x63,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x22, 0x65, 0x0a, 0x1b, 0x47, 0x6f, 0x73, 0x73, 0x69, 0x70, 0x42, 0x61, 0x74,
	0x63, 0x68, 0x42, 0x79, 0x42, 0x61, 0x74, 0x63, 0x68, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0c, 0x74, 0x69, 0x6d, 0x65,
	0x5f, 0x74, 0x6f, 0x5f, 0x6c, 0x69, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a,
	0x74, 0x69, 0x6d, 0x65, 0x54, 0x6f, 0x4c, 0x69, 0x76, 0x65, 0x22, 0x6d, 0x0a, 0x21, 0x47, 0x6f,
	0x73, 0x73, 0x69, 0x70, 0x42, 0x61, 0x74, 0x63, 0x68, 0x42, 0x79, 0x54, 0x72, 0x61, 0x6e, 0x73,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x69, 0x64,
	0x73, 0x12, 0x14, 0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0c, 0x74, 0x69, 0x6d, 0x65, 0x5f,
	0x74, 0x6f, 0x5f, 0x6c, 0x69, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x74,
	0x69, 0x6d, 0x65, 0x54, 0x6f, 0x4c, 0x69, 0x76, 0x65, 0x22, 0x71, 0x0a, 0x16, 0x47, 0x6f, 0x73,
	0x73, 0x69, 0x70, 0x43, 0x6f, 0x6e, 0x73, 0x65, 0x6e, 0x73, 0x75, 0x73, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0c, 0x74, 0x69,
	0x6d, 0x65, 0x5f, 0x74, 0x6f, 0x5f, 0x6c, 0x69, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0a, 0x74, 0x69, 0x6d, 0x65, 0x54, 0x6f, 0x4c, 0x69, 0x76, 0x65, 0x42, 0x26, 0x0a, 0x15,
	0x73, 0x61, 0x77, 0x74, 0x6f, 0x6f, 0x74, 0x68, 0x2e, 0x73, 0x64, 0x6b, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x50, 0x01, 0x5a, 0x0b, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b,
	0x5f, 0x70, 0x62, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_network_pb2_network_proto_rawDescOnce sync.Once
	file_protobuf_network_pb2_network_proto_rawDescData = file_protobuf_network_pb2_network_proto_rawDesc
)

func file_protobuf_network_pb2_network_proto_rawDescGZIP() []byte {
	file_protobuf_network_pb2_network_proto_rawDescOnce.Do(func() {
		file_protobuf_network_pb2_network_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_network_pb2_network_proto_rawDescData)
	})
	return file_protobuf_network_pb2_network_proto_rawDescData
}

var file_protobuf_network_pb2_network_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protobuf_network_pb2_network_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_protobuf_network_pb2_network_proto_goTypes = []interface{}{
	(GossipMessage_ContentType)(0),            // 0: GossipMessage.ContentType
	(NetworkAcknowledgement_Status)(0),        // 1: NetworkAcknowledgement.Status
	(*DisconnectMessage)(nil),                 // 2: DisconnectMessage
	(*PeerRegisterRequest)(nil),               // 3: PeerRegisterRequest
	(*PeerUnregisterRequest)(nil),             // 4: PeerUnregisterRequest
	(*GetPeersRequest)(nil),                   // 5: GetPeersRequest
	(*GetPeersResponse)(nil),                  // 6: GetPeersResponse
	(*PingRequest)(nil),                       // 7: PingRequest
	(*PingResponse)(nil),                      // 8: PingResponse
	(*GossipMessage)(nil),                     // 9: GossipMessage
	(*NetworkAcknowledgement)(nil),            // 10: NetworkAcknowledgement
	(*GossipBlockRequest)(nil),                // 11: GossipBlockRequest
	(*GossipBlockResponse)(nil),               // 12: GossipBlockResponse
	(*GossipBatchResponse)(nil),               // 13: GossipBatchResponse
	(*GossipBatchByBatchIdRequest)(nil),       // 14: GossipBatchByBatchIdRequest
	(*GossipBatchByTransactionIdRequest)(nil), // 15: GossipBatchByTransactionIdRequest
	(*GossipConsensusMessage)(nil),            // 16: GossipConsensusMessage
}
var file_protobuf_network_pb2_network_proto_depIdxs = []int32{
	0, // 0: GossipMessage.content_type:type_name -> GossipMessage.ContentType
	1, // 1: NetworkAcknowledgement.status:type_name -> NetworkAcknowledgement.Status
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protobuf_network_pb2_network_proto_init() }
func file_protobuf_network_pb2_network_proto_init() {
	if File_protobuf_network_pb2_network_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_network_pb2_network_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisconnectMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_network_pb2_network_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PeerRegisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_network_pb2_network_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PeerUnregisterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_network_pb2_network_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPeersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_network_pb2_network_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPeersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_network_pb2_network_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_network_pb2_network_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_network_pb2_network_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GossipMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_network_pb2_network_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkAcknowledgement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_network_pb2_network_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GossipBlockRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_network_pb2_network_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GossipBlockResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_network_pb2_network_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GossipBatchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_network_pb2_network_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GossipBatchByBatchIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_network_pb2_network_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GossipBatchByTransactionIdRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_network_pb2_network_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GossipConsensusMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_network_pb2_network_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_network_pb2_network_proto_goTypes,
		DependencyIndexes: file_protobuf_network_pb2_network_proto_depIdxs,
		EnumInfos:         file_protobuf_network_pb2_network_proto_enumTypes,
		MessageInfos:      file_protobuf_network_pb2_network_proto_msgTypes,
	}.Build()
	File_protobuf_network_pb2_network_proto = out.File
	file_protobuf_network_pb2_network_proto_rawDesc = nil
	file_protobuf_network_pb2_network_proto_goTypes = nil
	file_protobuf_network_pb2_network_proto_depIdxs = nil
}
