// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf/transaction_receipt_pb2/transaction_receipt.proto

package txn_receipt_pb2

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	events_pb2 "protobuf/events_pb2"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StateChange_Type int32

const (
	StateChange_TYPE_UNSET StateChange_Type = 0
	StateChange_SET        StateChange_Type = 1
	StateChange_DELETE     StateChange_Type = 2
)

var StateChange_Type_name = map[int32]string{
	0: "TYPE_UNSET",
	1: "SET",
	2: "DELETE",
}

var StateChange_Type_value = map[string]int32{
	"TYPE_UNSET": 0,
	"SET":        1,
	"DELETE":     2,
}

func (x StateChange_Type) String() string {
	return proto.EnumName(StateChange_Type_name, int32(x))
}

func (StateChange_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_226aafec243c4eb6, []int{1, 0}
}

type TransactionReceipt struct {
	// State changes made by this transaction
	// StateChange is defined in protos/transaction_receipt.proto
	StateChanges []*StateChange `protobuf:"bytes,1,rep,name=state_changes,json=stateChanges,proto3" json:"state_changes,omitempty"`
	// Events fired by this transaction
	Events []*events_pb2.Event `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	// Transaction family defined data
	Data                 [][]byte `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	TransactionId        string   `protobuf:"bytes,4,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TransactionReceipt) Reset()         { *m = TransactionReceipt{} }
func (m *TransactionReceipt) String() string { return proto.CompactTextString(m) }
func (*TransactionReceipt) ProtoMessage()    {}
func (*TransactionReceipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_226aafec243c4eb6, []int{0}
}

func (m *TransactionReceipt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionReceipt.Unmarshal(m, b)
}
func (m *TransactionReceipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionReceipt.Marshal(b, m, deterministic)
}
func (m *TransactionReceipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionReceipt.Merge(m, src)
}
func (m *TransactionReceipt) XXX_Size() int {
	return xxx_messageInfo_TransactionReceipt.Size(m)
}
func (m *TransactionReceipt) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionReceipt.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionReceipt proto.InternalMessageInfo

func (m *TransactionReceipt) GetStateChanges() []*StateChange {
	if m != nil {
		return m.StateChanges
	}
	return nil
}

func (m *TransactionReceipt) GetEvents() []*events_pb2.Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *TransactionReceipt) GetData() [][]byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *TransactionReceipt) GetTransactionId() string {
	if m != nil {
		return m.TransactionId
	}
	return ""
}

//  StateChange objects have the type of SET, which is either an insert or
//  update, or DELETE. Items marked as a DELETE will have no byte value.
type StateChange struct {
	Address              string           `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Value                []byte           `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Type                 StateChange_Type `protobuf:"varint,3,opt,name=type,proto3,enum=StateChange_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *StateChange) Reset()         { *m = StateChange{} }
func (m *StateChange) String() string { return proto.CompactTextString(m) }
func (*StateChange) ProtoMessage()    {}
func (*StateChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_226aafec243c4eb6, []int{1}
}

func (m *StateChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateChange.Unmarshal(m, b)
}
func (m *StateChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateChange.Marshal(b, m, deterministic)
}
func (m *StateChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateChange.Merge(m, src)
}
func (m *StateChange) XXX_Size() int {
	return xxx_messageInfo_StateChange.Size(m)
}
func (m *StateChange) XXX_DiscardUnknown() {
	xxx_messageInfo_StateChange.DiscardUnknown(m)
}

var xxx_messageInfo_StateChange proto.InternalMessageInfo

func (m *StateChange) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *StateChange) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *StateChange) GetType() StateChange_Type {
	if m != nil {
		return m.Type
	}
	return StateChange_TYPE_UNSET
}

// A collection of state changes.
type StateChangeList struct {
	StateChanges         []*StateChange `protobuf:"bytes,1,rep,name=state_changes,json=stateChanges,proto3" json:"state_changes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *StateChangeList) Reset()         { *m = StateChangeList{} }
func (m *StateChangeList) String() string { return proto.CompactTextString(m) }
func (*StateChangeList) ProtoMessage()    {}
func (*StateChangeList) Descriptor() ([]byte, []int) {
	return fileDescriptor_226aafec243c4eb6, []int{2}
}

func (m *StateChangeList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateChangeList.Unmarshal(m, b)
}
func (m *StateChangeList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateChangeList.Marshal(b, m, deterministic)
}
func (m *StateChangeList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateChangeList.Merge(m, src)
}
func (m *StateChangeList) XXX_Size() int {
	return xxx_messageInfo_StateChangeList.Size(m)
}
func (m *StateChangeList) XXX_DiscardUnknown() {
	xxx_messageInfo_StateChangeList.DiscardUnknown(m)
}

var xxx_messageInfo_StateChangeList proto.InternalMessageInfo

func (m *StateChangeList) GetStateChanges() []*StateChange {
	if m != nil {
		return m.StateChanges
	}
	return nil
}

func init() {
	proto.RegisterEnum("StateChange_Type", StateChange_Type_name, StateChange_Type_value)
	proto.RegisterType((*TransactionReceipt)(nil), "TransactionReceipt")
	proto.RegisterType((*StateChange)(nil), "StateChange")
	proto.RegisterType((*StateChangeList)(nil), "StateChangeList")
}

func init() {
	proto.RegisterFile("protobuf/transaction_receipt_pb2/transaction_receipt.proto", fileDescriptor_226aafec243c4eb6)
}

var fileDescriptor_226aafec243c4eb6 = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x51, 0x4f, 0x4b, 0xfb, 0x40,
	0x10, 0xfd, 0x6d, 0x93, 0x5f, 0x8a, 0xd3, 0xf4, 0x8f, 0x8b, 0xc2, 0xe2, 0x41, 0x42, 0xa0, 0x10,
	0x14, 0x22, 0xd6, 0x9b, 0x47, 0x6d, 0x0e, 0x42, 0x91, 0xb2, 0x8d, 0x07, 0xbd, 0x84, 0x6d, 0xb3,
	0xda, 0xa0, 0x24, 0x21, 0x3b, 0xad, 0xf6, 0x63, 0xf8, 0x15, 0xfc, 0xa4, 0xb2, 0x1b, 0x6b, 0x23,
	0x78, 0xf2, 0xf6, 0xde, 0x9b, 0xf7, 0x66, 0x67, 0x67, 0xe0, 0xb2, 0xac, 0x0a, 0x2c, 0xe6, 0xab,
	0xc7, 0x33, 0xac, 0x44, 0xae, 0xc4, 0x02, 0xb3, 0x22, 0x4f, 0x2a, 0xb9, 0x90, 0x59, 0x89, 0x49,
	0x39, 0x1f, 0xfd, 0xa6, 0x87, 0x26, 0x74, 0xe4, 0x7d, 0x67, 0xe5, 0x5a, 0xe6, 0xa8, 0x8c, 0xbd,
	0x86, 0xb5, 0xc3, 0xff, 0x20, 0x40, 0xe3, 0x5d, 0x9e, 0xd7, 0x71, 0x7a, 0x0e, 0x5d, 0x85, 0x02,
	0x65, 0xb2, 0x58, 0x8a, 0xfc, 0x49, 0x2a, 0x46, 0x3c, 0x2b, 0xe8, 0x8c, 0xdc, 0x70, 0xa6, 0xd5,
	0x6b, 0x23, 0x72, 0x57, 0xed, 0x88, 0xa2, 0xc7, 0xe0, 0xd4, 0x9d, 0x59, 0xcb, 0x78, 0x9d, 0x30,
	0xd2, 0x94, 0x7f, 0xa9, 0x94, 0x82, 0x9d, 0x0a, 0x14, 0xcc, 0xf2, 0xac, 0xc0, 0xe5, 0x06, 0xd3,
	0x21, 0xf4, 0x9a, 0xc3, 0x67, 0x29, 0xb3, 0x3d, 0x12, 0xec, 0xf1, 0x6e, 0x43, 0xbd, 0x49, 0xfd,
	0x77, 0x02, 0x9d, 0xc6, 0xc3, 0x94, 0x41, 0x5b, 0xa4, 0x69, 0x25, 0x95, 0x9e, 0x4b, 0xfb, 0xb7,
	0x94, 0x1e, 0xc0, 0xff, 0xb5, 0x78, 0x59, 0x49, 0xd6, 0xf2, 0x48, 0xe0, 0xf2, 0x9a, 0xd0, 0x21,
	0xd8, 0xb8, 0x29, 0x25, 0xb3, 0x3c, 0x12, 0xf4, 0x46, 0xfb, 0xcd, 0x4f, 0x84, 0xf1, 0xa6, 0x94,
	0xdc, 0x94, 0xfd, 0x53, 0xb0, 0x35, 0xa3, 0x3d, 0x80, 0xf8, 0x7e, 0x1a, 0x25, 0x77, 0xb7, 0xb3,
	0x28, 0x1e, 0xfc, 0xa3, 0x6d, 0xb0, 0x34, 0x20, 0x14, 0xc0, 0x19, 0x47, 0x93, 0x28, 0x8e, 0x06,
	0x2d, 0x7f, 0x0c, 0xfd, 0x46, 0x9b, 0x49, 0xa6, 0xfe, 0xb2, 0xb4, 0xab, 0x13, 0x38, 0x54, 0xe2,
	0x15, 0x8b, 0x02, 0x97, 0xa1, 0x4a, 0x9f, 0xc3, 0xed, 0xbd, 0xa6, 0xe4, 0xa1, 0x8f, 0x6f, 0x3f,
	0xce, 0x3c, 0x77, 0x4c, 0xf1, 0xe2, 0x33, 0x00, 0x00, 0xff, 0xff, 0xe2, 0xba, 0xff, 0x25, 0x11,
	0x02, 0x00, 0x00,
}
